/**
 * Boss loot tables (DATA) + pure validators. The live game imports BOSS_DROP_TABLE_BY_LABEL
 * from here; tests import the validators. Tune boss drops HERE, not in app.monolith.js.
 * Each entry is { id, chance } with chance in (0, 1]. See COOKBOOK.md recipe 3.
 */

const BOSS_GEM_ITEM_IDS = [
  "accuracygem",
  "agilitygem",
  "braverygem",
  "disillusiongem",
  "endurancegem",
  "evilslayergem",
  "freezinggem",
  "magicgem",
  "poisongem",
  "protectiongem",
  "soulgem",
  "stormgem",
];
const BOSS_ORB_ITEM_IDS = [
  "accuracyorb",
  "agilityorb",
  "braveryorb",
  "disillusionorb",
  "enduranceorb",
  "evilslayerorb",
  "freezingorb",
  "magicorb",
  "poisonorb",
  "protectionorb",
  "soulorb",
  "stormorb",
];
function bossGemDrops(chance = 0.05) {
  return BOSS_GEM_ITEM_IDS.map((id) => ({ id, chance }));
}
function bossOrbDrops(chance = 0.01) {
  return BOSS_ORB_ITEM_IDS.map((id) => ({ id, chance }));
}

/** Top-tier (Holy) stones — level-0 max-stat Crystal Stone slot items. */
const BOSS_TOP_TIER_STONE_ITEM_IDS = [
  "health-stone",
  "magic-stone",
  "power-stone",
  "dcstone",
  "mcstone",
  "scstone",
];
function bossTopTierStoneDrops(chance = 0.03) {
  return BOSS_TOP_TIER_STONE_ITEM_IDS.map((id) => ({ id, chance }));
}

const BDD_SCORPION_IWT_PREMIUM_DROPS = [
  { id: "8-trigram-wheel", chance: 0.025 },
  { id: "adamantine-necklace", chance: 0.025 },
  { id: "baek-ta-glove", chance: 0.025 },
  { id: "black-boots", chance: 0.01 },
  { id: "boundless-ring", chance: 0.025 },
  { id: "great-helmet", chance: 0.01 },
  { id: "hang-ma-wheel", chance: 0.025 },
  { id: "helmet-of-hero", chance: 0.01 },
  { id: "hero-necklace", chance: 0.025 },
  { id: "leather-boots", chance: 0.025 },
  { id: "noble-ring", chance: 0.05 },
  { id: "requiem-necklace", chance: 0.025 },
  { id: "soul-ring", chance: 0.05 },
  { id: "spirit-reformer", chance: 0.025 },
  { id: "tae-guk-ring", chance: 0.025 },
  { id: "tao-coronet", chance: 0.01 },
  { id: "thunder-ring", chance: 0.025 },
  { id: "wisdom-coronet", chance: 0.01 },
];

const BLACK_DRAGON_ARMOR_MYTHICAL_DROPS = [
  { id: "black-dragon-armor-m-1", chance: 0.005 },
  { id: "black-dragon-armor-m-2", chance: 0.005 },
  { id: "black-dragon-armor-m-3", chance: 0.005 },
];

function crystalArmourDrops(chance) {
  return [{ id: "crystal-armour", chance }];
}

const CRYSTAL_ARMOUR_COMMON_BOSS_DROPS = crystalArmourDrops(0.005);
const CRYSTAL_ARMOUR_RARE_BOSS_DROPS = crystalArmourDrops(0.01);

const KING_HOG_PREMIUM_DROPS = [
  { id: "8-trigram-wheel", chance: 0.05 },
  { id: "adamantine-necklace", chance: 0.05 },
  { id: "baek-ta-glove", chance: 0.05 },
  { id: "black-boots", chance: 0.1 },
  { id: "bok-ma-wheel", chance: 0.05 },
  { id: "gold-belt", chance: 0.1 },
  { id: "great-helmet", chance: 0.05 },
  { id: "hang-ma-wheel", chance: 0.05 },
  { id: "helmet-of-hero", chance: 0.05 },
  { id: "hero-necklace", chance: 0.05 },
  { id: "holy-tao-wheel", chance: 0.05 },
  { id: "noble-ring", chance: 0.05 },
  { id: "requiem-necklace", chance: 0.05 },
  { id: "soul-ring", chance: 0.05 },
  { id: "spirit-reformer", chance: 0.05 },
  { id: "tao-coronet", chance: 0.05 },
  { id: "wisdom-coronet", chance: 0.05 },
];

const WOMA_TAURUS_BOSS_DROPS = {
  gold: 20000,
  items: [
    { id: "wooma-heart", chance: 0.1 },
    { id: "awakening-soul", chance: 0.1 },
    { id: "great-axe", chance: 0.3 },
    { id: "mage-staff", chance: 0.3 },
    { id: "serpent-sword", chance: 0.3 },
    { id: "dragon-sword", chance: 1 / 55 },
    { id: "dcstone-l", chance: 0.2 },
    { id: "mcstone-l", chance: 0.2 },
    { id: "scstone-l", chance: 0.2 },
    { id: "expel-ring", chance: 0.2 },
    { id: "spell-bracelet", chance: 0.2 },
    { id: "black-iron-bracelet", chance: 0.2 },
    { id: "book-frost-crunch", chance: 0.2 },
    { id: "book-half-moon", chance: 0.1 },
    { id: "black-boots", chance: 0.05 },
    ...CRYSTAL_ARMOUR_COMMON_BOSS_DROPS,
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const INCARNATED_WT_BOSS_DROPS = {
  gold: 20000,
  items: [
    { id: "awakening-soul", chance: 0.2 },
    { id: "book-cross-half-moon", chance: 0.03 },
    { id: "dragon-slayer", chance: 1 / 10 },
    { id: "dragon-staff", chance: 1 / 10 },
    { id: "soul-sabre", chance: 1 / 10 },
    { id: "skeleton-helmet", chance: 1 / 10 },
    { id: "steel-armour", chance: 0.05 },
    { id: "titan-armour", chance: 0.05 },
    { id: "dragon-robe", chance: 0.05 },
    { id: "claw-necklace", chance: 0.1 },
    { id: "pearl-necklace", chance: 0.1 },
    { id: "life-necklace", chance: 0.1 },
    { id: "spirit-necklace", chance: 0.1 },
    { id: "gale-necklace", chance: 0.1 },
    { id: "green-bead", chance: 0.05 },
    { id: "demonic-bells", chance: 0.05 },
    { id: "soul-necklace", chance: 0.05 },
    { id: "knight-bracelet", chance: 0.05 },
    { id: "soul-spring-bracelet", chance: 0.05 },
    { id: "dragon-bracelet", chance: 0.05 },
    { id: "dragon-ring", chance: 0.1 },
    { id: "ruby-ring", chance: 0.1 },
    { id: "platinum-ring", chance: 0.1 },
    { id: "spirit-ring", chance: 0.05 },
    { id: "power-ring", chance: 0.05 },
    { id: "violet-ring", chance: 0.05 },
    { id: "titan-ring", chance: 0.05 },
    { id: "judgement-mace", chance: 0.05 },
    { id: "war-mage-staff", chance: 0.05 },
    { id: "soul-spring-wand", chance: 0.05 },
    { id: "war-spirit-blade", chance: 0.06 },
    { id: "magic-scythe", chance: 0.06 },
    { id: "stone-bamboo-fan", chance: 0.06 },
    { id: "black-iron-helmet", chance: 0.05 },
    { id: "dragon-slayer", chance: 0.025 },
    { id: "dragon-staff", chance: 0.025 },
    { id: "soul-sabre", chance: 0.025 },
    ...bossTopTierStoneDrops(0.03),
    ...BDD_SCORPION_IWT_PREMIUM_DROPS,
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const EVIL_SNAKE_BOSS_DROPS = {
  gold: 20000,
  items: [
    { id: "awakening-soul", chance: 0.1 },
    { id: "great-axe", chance: 0.3 },
    { id: "mage-staff", chance: 0.3 },
    { id: "serpent-sword", chance: 0.3 },
    { id: "dragon-sword", chance: 1 / 150 },
    { id: "dcstone-l", chance: 0.2 },
    { id: "mcstone-l", chance: 0.2 },
    { id: "scstone-l", chance: 0.2 },
    { id: "expel-ring", chance: 0.2 },
    { id: "spell-bracelet", chance: 0.2 },
    { id: "black-iron-bracelet", chance: 0.2 },
    { id: "black-boots", chance: 0.05 },
    ...CRYSTAL_ARMOUR_COMMON_BOSS_DROPS,
    ...BLACK_DRAGON_ARMOR_MYTHICAL_DROPS,
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const ZUMA_TAURUS_BOSS_DROPS = {
  gold: 20000,
  items: [
    { id: "zuma-relic", chance: 0.1 },
    { id: "awakening-soul", chance: 0.2 },
    { id: "book-twin-drake-blade", chance: 0.1 },
    { id: "zuma-judgement-mace", chance: 1 / 10 },
    { id: "zuma-war-mage-staff", chance: 1 / 10 },
    { id: "zuma-soul-spring-wand", chance: 1 / 10 },
    { id: "skeleton-helmet", chance: 1 / 10 },
    { id: "iron-armour", chance: 0.05 },
    { id: "wizard-robe", chance: 0.05 },
    { id: "pearl-armour", chance: 0.05 },
    { id: "claw-necklace", chance: 0.1 },
    { id: "pearl-necklace", chance: 0.1 },
    { id: "life-necklace", chance: 0.1 },
    { id: "spirit-necklace", chance: 0.1 },
    { id: "gale-necklace", chance: 0.1 },
    { id: "green-bead", chance: 0.05 },
    { id: "demonic-bells", chance: 0.05 },
    { id: "soul-necklace", chance: 0.05 },
    { id: "knight-bracelet", chance: 0.05 },
    { id: "soul-spring-bracelet", chance: 0.05 },
    { id: "dragon-bracelet", chance: 0.05 },
    { id: "dragon-ring", chance: 0.1 },
    { id: "ruby-ring", chance: 0.1 },
    { id: "platinum-ring", chance: 0.1 },
    { id: "spirit-ring", chance: 0.05 },
    { id: "power-ring", chance: 0.05 },
    { id: "violet-ring", chance: 0.05 },
    { id: "titan-ring", chance: 0.05 },
    { id: "judgement-mace", chance: 0.05 },
    { id: "war-mage-staff", chance: 0.05 },
    { id: "soul-spring-wand", chance: 0.05 },
    { id: "war-spirit-blade", chance: 0.06 },
    { id: "magic-scythe", chance: 0.06 },
    { id: "stone-bamboo-fan", chance: 0.06 },
    { id: "black-iron-helmet", chance: 0.05 },
    { id: "dragon-slayer", chance: 0.025 },
    { id: "dragon-staff", chance: 0.025 },
    { id: "soul-sabre", chance: 0.025 },
    ...CRYSTAL_ARMOUR_COMMON_BOSS_DROPS,
    ...BLACK_DRAGON_ARMOR_MYTHICAL_DROPS,
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const INCARNATED_ZT_BOSS_DROPS = {
  gold: 20000,
  items: [
    { id: "stone-heart", chance: 0.1 },
    { id: "zuma-relic", chance: 0.1 },
    { id: "awakening-soul", chance: 0.2 },
    { id: "book-twin-drake-blade", chance: 0.1 },
    { id: "book-protection-field", chance: 0.1 },
    { id: "book-mirroring", chance: 0.1 },
    { id: "zuma-judgement-mace", chance: 1 / 10 },
    { id: "zuma-war-mage-staff", chance: 1 / 10 },
    { id: "zuma-soul-spring-wand", chance: 1 / 10 },
    { id: "skeleton-helmet", chance: 1 / 10 },
    { id: "iron-armour", chance: 0.05 },
    { id: "wizard-robe", chance: 0.05 },
    { id: "pearl-armour", chance: 0.05 },
    { id: "claw-necklace", chance: 0.1 },
    { id: "pearl-necklace", chance: 0.1 },
    { id: "life-necklace", chance: 0.1 },
    { id: "spirit-necklace", chance: 0.1 },
    { id: "gale-necklace", chance: 0.1 },
    { id: "green-bead", chance: 0.05 },
    { id: "demonic-bells", chance: 0.05 },
    { id: "soul-necklace", chance: 0.05 },
    { id: "knight-bracelet", chance: 0.05 },
    { id: "soul-spring-bracelet", chance: 0.05 },
    { id: "dragon-bracelet", chance: 0.05 },
    { id: "dragon-ring", chance: 0.1 },
    { id: "ruby-ring", chance: 0.1 },
    { id: "platinum-ring", chance: 0.1 },
    { id: "spirit-ring", chance: 0.05 },
    { id: "power-ring", chance: 0.05 },
    { id: "violet-ring", chance: 0.05 },
    { id: "titan-ring", chance: 0.05 },
    { id: "judgement-mace", chance: 0.05 },
    { id: "war-mage-staff", chance: 0.05 },
    { id: "soul-spring-wand", chance: 0.05 },
    { id: "war-spirit-blade", chance: 0.06 },
    { id: "magic-scythe", chance: 0.06 },
    { id: "stone-bamboo-fan", chance: 0.06 },
    { id: "black-iron-helmet", chance: 0.05 },
    { id: "dragon-slayer", chance: 0.025 },
    { id: "dragon-staff", chance: 0.025 },
    { id: "soul-sabre", chance: 0.025 },
    { id: "heaven-sword", chance: 0.005 },
    { id: "heaven-armour", chance: 0.005 },
    ...bossTopTierStoneDrops(0.03),
    ...KING_HOG_PREMIUM_DROPS,
    { id: "oma-spirit-ring", chance: 0.05 },
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.02),
  ],
};
const EVIL_CENTIPEDE_BOSS_DROPS = {
  gold: 12500,
  items: [
    { id: "book-ultimate-enhancer", chance: 0.15 },
    { id: "dragon-sword", chance: 1 / 25 },
    { id: "awakening-soul", chance: 0.2 },
    { id: "great-axe", chance: 1 / 20 },
    { id: "mage-staff", chance: 1 / 20 },
    { id: "serpent-sword", chance: 1 / 20 },
    { id: "skeleton-helmet", chance: 1 / 20 },
    { id: "claw-necklace", chance: 0.05 },
    { id: "pearl-necklace", chance: 0.05 },
    { id: "life-necklace", chance: 0.05 },
    { id: "spirit-necklace", chance: 0.05 },
    { id: "gale-necklace", chance: 0.05 },
    { id: "green-bead", chance: 0.025 },
    { id: "demonic-bells", chance: 0.025 },
    { id: "soul-necklace", chance: 0.025 },
    { id: "knight-bracelet", chance: 0.025 },
    { id: "soul-spring-bracelet", chance: 0.025 },
    { id: "dragon-bracelet", chance: 0.025 },
    { id: "dragon-ring", chance: 0.05 },
    { id: "ruby-ring", chance: 0.05 },
    { id: "platinum-ring", chance: 0.05 },
    { id: "spirit-ring", chance: 0.025 },
    { id: "power-ring", chance: 0.025 },
    { id: "violet-ring", chance: 0.025 },
    { id: "titan-ring", chance: 0.025 },
    { id: "judgement-mace", chance: 0.05 },
    { id: "war-mage-staff", chance: 0.05 },
    { id: "soul-spring-wand", chance: 0.05 },
    { id: "black-iron-helmet", chance: 0.025 },
    { id: "dragon-slayer", chance: 0.025 },
    { id: "dragon-staff", chance: 0.025 },
    { id: "soul-sabre", chance: 0.025 },
    ...CRYSTAL_ARMOUR_COMMON_BOSS_DROPS,
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const BONE_LORD_BOSS_DROPS = {
  gold: 16000,
  items: [
    { id: "book-summon-shinsu", chance: 0.1 },
    { id: "book-turn-undead", chance: 0.1 },
    { id: "book-vampirism", chance: 0.1 },
    { id: "awakening-soul", chance: 0.15 },
    { id: "judgement-mace", chance: 0.07 },
    { id: "war-mage-staff", chance: 0.07 },
    { id: "soul-spring-wand", chance: 0.07 },
    { id: "war-spirit-blade", chance: 0.03 },
    { id: "magic-scythe", chance: 0.03 },
    { id: "stone-bamboo-fan", chance: 0.03 },
    { id: "skeleton-helmet", chance: 1 / 15 },
    { id: "black-iron-helmet", chance: 0.04 },
    { id: "iron-armour", chance: 0.05 },
    { id: "wizard-robe", chance: 0.05 },
    { id: "pearl-armour", chance: 0.05 },
    { id: "claw-necklace", chance: 0.08 },
    { id: "pearl-necklace", chance: 0.08 },
    { id: "life-necklace", chance: 0.08 },
    { id: "spirit-necklace", chance: 0.08 },
    { id: "gale-necklace", chance: 0.07 },
    { id: "green-bead", chance: 0.04 },
    { id: "demonic-bells", chance: 0.04 },
    { id: "soul-necklace", chance: 0.04 },
    { id: "knight-bracelet", chance: 0.04 },
    { id: "soul-spring-bracelet", chance: 0.04 },
    { id: "dragon-bracelet", chance: 0.04 },
    { id: "dragon-ring", chance: 0.08 },
    { id: "ruby-ring", chance: 0.08 },
    { id: "platinum-ring", chance: 0.08 },
    { id: "spirit-ring", chance: 0.04 },
    { id: "power-ring", chance: 0.04 },
    { id: "violet-ring", chance: 0.04 },
    { id: "titan-ring", chance: 0.04 },
    { id: "death-gauntlet", chance: 0.03 },
    { id: "smash-wheel", chance: 0.025 },
    { id: "smash-ring", chance: 0.025 },
    { id: "dragon-slayer", chance: 0.025 },
    { id: "dragon-staff", chance: 0.025 },
    { id: "soul-sabre", chance: 0.025 },
    ...CRYSTAL_ARMOUR_COMMON_BOSS_DROPS,
    ...BLACK_DRAGON_ARMOR_MYTHICAL_DROPS,
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const KING_SCORPION_BOSS_DROPS = {
  gold: 16000,
  items: [
    { id: "awakening-soul", chance: 0.15 },
    { id: "judgement-mace", chance: 0.07 },
    { id: "war-mage-staff", chance: 0.07 },
    { id: "soul-spring-wand", chance: 0.07 },
    { id: "war-spirit-blade", chance: 0.03 },
    { id: "magic-scythe", chance: 0.03 },
    { id: "stone-bamboo-fan", chance: 0.03 },
    { id: "skeleton-helmet", chance: 1 / 15 },
    { id: "black-iron-helmet", chance: 0.04 },
    { id: "iron-armour", chance: 0.05 },
    { id: "wizard-robe", chance: 0.05 },
    { id: "pearl-armour", chance: 0.05 },
    { id: "claw-necklace", chance: 0.08 },
    { id: "pearl-necklace", chance: 0.08 },
    { id: "life-necklace", chance: 0.08 },
    { id: "spirit-necklace", chance: 0.08 },
    { id: "gale-necklace", chance: 0.07 },
    { id: "green-bead", chance: 0.04 },
    { id: "demonic-bells", chance: 0.04 },
    { id: "soul-necklace", chance: 0.04 },
    { id: "knight-bracelet", chance: 0.04 },
    { id: "soul-spring-bracelet", chance: 0.04 },
    { id: "dragon-bracelet", chance: 0.04 },
    { id: "dragon-ring", chance: 0.08 },
    { id: "ruby-ring", chance: 0.08 },
    { id: "platinum-ring", chance: 0.08 },
    { id: "spirit-ring", chance: 0.04 },
    { id: "power-ring", chance: 0.04 },
    { id: "violet-ring", chance: 0.04 },
    { id: "titan-ring", chance: 0.04 },
    { id: "death-gauntlet", chance: 0.03 },
    { id: "smash-wheel", chance: 0.025 },
    { id: "smash-ring", chance: 0.025 },
    { id: "dragon-sword", chance: 1 / 70 },
    { id: "dragon-slayer", chance: 0.025 },
    { id: "dragon-staff", chance: 0.025 },
    { id: "soul-sabre", chance: 0.025 },
    { id: "book-ice-storm", chance: 0.1 },
    ...BDD_SCORPION_IWT_PREMIUM_DROPS,
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const OMA_KING_SPIRIT_BOSS_DROPS = {
  gold: 35000,
  benedictionOils: 2,
  items: [
    { id: "book-flame-disruptor", chance: 0.1 },
    { id: "awakening-soul", chance: 0.5 },
    { id: "oma-spirit-ring", chance: 0.2 },
    { id: "oma-king-robe", chance: 0.03 },
    { id: "heaven-sword", chance: 0.005 },
    { id: "heaven-armour", chance: 0.005 },
    { id: "sword-of-war-god", chance: 0.03 },
    { id: "blade-of-sorcery", chance: 0.03 },
    { id: "dragon-slayer", chance: 0.06 },
    { id: "dragon-staff", chance: 0.06 },
    { id: "soul-sabre", chance: 0.06 },
    { id: "judgement-mace", chance: 0.15 },
    { id: "war-mage-staff", chance: 0.15 },
    { id: "soul-spring-wand", chance: 0.15 },
    { id: "war-spirit-blade", chance: 0.15 },
    { id: "magic-scythe", chance: 0.15 },
    { id: "stone-bamboo-fan", chance: 0.15 },
    { id: "steel-armour", chance: 0.1 },
    { id: "dragon-robe", chance: 0.1 },
    { id: "titan-armour", chance: 0.1 },
    { id: "skeleton-helmet", chance: 0.08 },
    { id: "black-iron-helmet", chance: 0.05 },
    { id: "shaman-helmet", chance: 0.05 },
    { id: "brass-helmet", chance: 0.04 },
    { id: "death-gauntlet", chance: 0.05 },
    { id: "claw-necklace", chance: 0.08 },
    { id: "pearl-necklace", chance: 0.08 },
    { id: "life-necklace", chance: 0.08 },
    { id: "spirit-necklace", chance: 0.08 },
    { id: "gale-necklace", chance: 0.07 },
    { id: "green-bead", chance: 0.05 },
    { id: "demonic-bells", chance: 0.05 },
    { id: "soul-necklace", chance: 0.05 },
    { id: "knight-bracelet", chance: 0.06 },
    { id: "soul-spring-bracelet", chance: 0.06 },
    { id: "dragon-bracelet", chance: 0.06 },
    { id: "dragon-ring", chance: 0.08 },
    { id: "ruby-ring", chance: 0.08 },
    { id: "platinum-ring", chance: 0.08 },
    { id: "power-ring", chance: 0.06 },
    { id: "titan-ring", chance: 0.06 },
    { id: "violet-ring", chance: 0.06 },
    { id: "spirit-ring", chance: 0.06 },
    { id: "expel-ring", chance: 0.06 },
    { id: "gale-ring", chance: 0.05 },
    { id: "impact-drug-m", chance: 0.12 },
    { id: "magic-drug-m", chance: 0.12 },
    { id: "taoist-drug-m", chance: 0.12 },
    ...CRYSTAL_ARMOUR_RARE_BOSS_DROPS,
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const MINOTAUR_KING_BOSS_DROPS = {
  gold: 25000,
  items: [
    { id: "book-mass-healing", chance: 0.1 },
    { id: "awakening-soul", chance: 0.22 },
    { id: "sword-of-war-god", chance: 0.01 },
    { id: "blade-of-sorcery", chance: 0.01 },
    { id: "heaven-sword", chance: 0.01 },
    { id: "steel-armour", chance: 0.06 },
    { id: "dragon-robe", chance: 0.06 },
    { id: "titan-armour", chance: 0.06 },
    { id: "dragon-slayer", chance: 0.03 },
    { id: "dragon-staff", chance: 0.03 },
    { id: "soul-sabre", chance: 0.03 },
    { id: "war-spirit-blade", chance: 0.05 },
    { id: "magic-scythe", chance: 0.05 },
    { id: "stone-bamboo-fan", chance: 0.05 },
    { id: "skeleton-helmet", chance: 0.08 },
    { id: "black-iron-helmet", chance: 0.05 },
    { id: "death-gauntlet", chance: 0.05 },
    { id: "claw-necklace", chance: 0.1 },
    { id: "pearl-necklace", chance: 0.1 },
    { id: "life-necklace", chance: 0.1 },
    { id: "spirit-necklace", chance: 0.1 },
    { id: "gale-necklace", chance: 0.08 },
    { id: "green-bead", chance: 0.05 },
    { id: "demonic-bells", chance: 0.05 },
    { id: "soul-necklace", chance: 0.05 },
    { id: "knight-bracelet", chance: 0.05 },
    { id: "soul-spring-bracelet", chance: 0.05 },
    { id: "dragon-bracelet", chance: 0.05 },
    { id: "dragon-ring", chance: 0.1 },
    { id: "ruby-ring", chance: 0.1 },
    { id: "platinum-ring", chance: 0.1 },
    { id: "spirit-ring", chance: 0.05 },
    { id: "power-ring", chance: 0.05 },
    { id: "violet-ring", chance: 0.05 },
    { id: "titan-ring", chance: 0.05 },
    { id: "impact-drug-m", chance: 0.12 },
    { id: "magic-drug-m", chance: 0.12 },
    { id: "taoist-drug-m", chance: 0.12 },
    ...CRYSTAL_ARMOUR_COMMON_BOSS_DROPS,
    ...BLACK_DRAGON_ARMOR_MYTHICAL_DROPS,
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const YIMOOGI_BOSS_DROPS = {
  gold: 15000,
  benedictionOils: 1,
  items: [
    { id: "awakening-soul", chance: 0.35 },
    { id: "book-summon-holy-deva", chance: 0.1 },
    { id: "judgement-mace", chance: 0.1 },
    { id: "war-mage-staff", chance: 0.1 },
    { id: "soul-spring-wand", chance: 0.1 },
    { id: "war-spirit-blade", chance: 0.05 },
    { id: "magic-scythe", chance: 0.05 },
    { id: "stone-bamboo-fan", chance: 0.05 },
    { id: "dragon-slayer", chance: 0.025 },
    { id: "dragon-staff", chance: 0.025 },
    { id: "soul-sabre", chance: 0.025 },
    { id: "steel-armour", chance: 0.1 },
    { id: "dragon-robe", chance: 0.1 },
    { id: "titan-armour", chance: 0.1 },
    { id: "black-iron-helmet", chance: 0.1 },
    { id: "helmet-of-hero", chance: 0.1 },
    { id: "great-helmet", chance: 0.1 },
    { id: "wisdom-coronet", chance: 0.1 },
    { id: "tao-coronet", chance: 0.1 },
    { id: "silk-boots", chance: 0.05 },
    { id: "black-boots", chance: 0.05 },
    { id: "dragon-boots", chance: 0.05 },
    { id: "chain-belt", chance: 0.05 },
    { id: "steel-belt", chance: 0.05 },
    { id: "gold-belt", chance: 0.05 },
    { id: "claw-necklace", chance: 0.1 },
    { id: "life-necklace", chance: 0.1 },
    { id: "pearl-necklace", chance: 0.1 },
    { id: "green-bead", chance: 0.05 },
    { id: "soul-necklace", chance: 0.05 },
    { id: "demonic-bells", chance: 0.05 },
    { id: "hero-necklace", chance: 0.03 },
    { id: "adamantine-necklace", chance: 0.03 },
    { id: "requiem-necklace", chance: 0.03 },
    { id: "gale-necklace", chance: 0.03 },
    { id: "gold-bracelet", chance: 0.1 },
    { id: "knight-bracelet", chance: 0.1 },
    { id: "spell-bracelet", chance: 0.1 },
    { id: "3rd-eye-bracelet", chance: 0.1 },
    { id: "steel-glove", chance: 0.1 },
    { id: "black-iron-bracelet", chance: 0.05 },
    { id: "dragon-bracelet", chance: 0.05 },
    { id: "soul-spring-bracelet", chance: 0.05 },
    { id: "8-trigram-wheel", chance: 0.05 },
    { id: "hang-ma-wheel", chance: 0.05 },
    { id: "bok-ma-wheel", chance: 0.05 },
    { id: "baek-ta-glove", chance: 0.03 },
    { id: "spirit-reformer", chance: 0.03 },
    { id: "holy-tao-wheel", chance: 0.03 },
    { id: "dragon-ring", chance: 0.1 },
    { id: "ruby-ring", chance: 0.1 },
    { id: "platinum-ring", chance: 0.1 },
    { id: "power-ring", chance: 0.05 },
    { id: "violet-ring", chance: 0.05 },
    { id: "titan-ring", chance: 0.05 },
    { id: "oma-spirit-ring", chance: 0.05 },
    { id: "noble-ring", chance: 0.03 },
    { id: "soul-ring", chance: 0.03 },
    { id: "boundless-ring", chance: 0.03 },
    { id: "thunder-ring", chance: 0.03 },
    { id: "tae-guk-ring", chance: 0.03 },
    { id: "sun-potion-medium", chance: 1 },
    { id: "sun-potion-medium", chance: 1 },
    { id: "sun-potion-medium", chance: 1 },
    { id: "sun-potion-medium", chance: 1 / 2 },
    { id: "sun-potion-medium", chance: 1 / 2 },
    { id: "sun-potion-medium", chance: 1 / 2 },
    { id: "sun-potion", chance: 1 },
    { id: "sun-potion", chance: 1 },
    { id: "sun-potion", chance: 1 },
    { id: "sun-potion", chance: 1 / 2 },
    { id: "sun-potion", chance: 1 / 2 },
    { id: "sun-potion", chance: 1 / 2 },
    { id: "sun-potion", chance: 1 / 2 },
    { id: "sun-potion", chance: 1 / 2 },
    { id: "magic-drug-s", chance: 1 / 60 },
    { id: "impact-drug-s", chance: 1 / 60 },
    { id: "taoist-drug-s", chance: 1 / 60 },
    ...CRYSTAL_ARMOUR_RARE_BOSS_DROPS,
    ...bossGemDrops(0.06),
    ...bossOrbDrops(0.012),
  ],
};
const KING_HOG_BOSS_DROPS = {
  gold: 35000,
  benedictionOils: 2,
  items: [
    { id: "hog-tooth", chance: 0.1 },
    { id: "awakening-soul", chance: 0.75 },
    { id: "book-blade-avalanche", chance: 0.1 },
    { id: "book-healing-circle", chance: 0.1 },
    { id: "oma-spirit-ring", chance: 0.2 },
    { id: "heaven-sword", chance: 0.005 },
    { id: "heaven-armour", chance: 0.005 },
    { id: "sword-of-war-god", chance: 0.03 },
    { id: "blade-of-sorcery", chance: 0.03 },
    { id: "dragon-slayer", chance: 0.06 },
    { id: "dragon-staff", chance: 0.06 },
    { id: "soul-sabre", chance: 0.06 },
    { id: "judgement-mace", chance: 0.15 },
    { id: "war-mage-staff", chance: 0.15 },
    { id: "soul-spring-wand", chance: 0.15 },
    { id: "war-spirit-blade", chance: 0.15 },
    { id: "magic-scythe", chance: 0.15 },
    { id: "stone-bamboo-fan", chance: 0.15 },
    { id: "steel-armour", chance: 0.1 },
    { id: "dragon-robe", chance: 0.1 },
    { id: "titan-armour", chance: 0.1 },
    { id: "skeleton-helmet", chance: 0.08 },
    { id: "black-iron-helmet", chance: 0.05 },
    { id: "shaman-helmet", chance: 0.05 },
    { id: "brass-helmet", chance: 0.04 },
    { id: "death-gauntlet", chance: 0.05 },
    { id: "claw-necklace", chance: 0.08 },
    { id: "pearl-necklace", chance: 0.08 },
    { id: "life-necklace", chance: 0.08 },
    { id: "spirit-necklace", chance: 0.08 },
    { id: "gale-necklace", chance: 0.07 },
    { id: "green-bead", chance: 0.05 },
    { id: "demonic-bells", chance: 0.05 },
    { id: "soul-necklace", chance: 0.05 },
    { id: "knight-bracelet", chance: 0.06 },
    { id: "soul-spring-bracelet", chance: 0.06 },
    { id: "dragon-bracelet", chance: 0.06 },
    { id: "dragon-ring", chance: 0.08 },
    { id: "ruby-ring", chance: 0.08 },
    { id: "platinum-ring", chance: 0.08 },
    { id: "power-ring", chance: 0.06 },
    { id: "titan-ring", chance: 0.06 },
    { id: "violet-ring", chance: 0.06 },
    { id: "spirit-ring", chance: 0.06 },
    { id: "expel-ring", chance: 0.06 },
    { id: "gale-ring", chance: 0.05 },
    { id: "impact-drug-m", chance: 0.12 },
    { id: "magic-drug-m", chance: 0.12 },
    { id: "taoist-drug-m", chance: 0.12 },
    ...bossTopTierStoneDrops(0.03),
    ...CRYSTAL_ARMOUR_RARE_BOSS_DROPS,
    ...KING_HOG_PREMIUM_DROPS,
    ...bossGemDrops(0.1),
    ...bossOrbDrops(0.02),
  ],
};
const RED_CAVERN_DEVOURER_BOSS_DROPS = {
  gold: 20000,
  benedictionOils: 1,
  items: [
    { id: "awakening-soul", chance: 0.5 },
    { id: "8-trigram-wheel", chance: 0.075 },
    { id: "bok-ma-wheel", chance: 0.075 },
    { id: "hang-ma-wheel", chance: 0.075 },
    { id: "dragon-slayer", chance: 0.075 },
    { id: "dragon-staff", chance: 0.075 },
    { id: "soul-sabre", chance: 0.075 },
    { id: "steel-gauntlet", chance: 0.075 },
    { id: "baek-ta-glove", chance: 0.05 },
    { id: "boundless-ring", chance: 0.05 },
    { id: "cloud-ring", chance: 0.05 },
    { id: "demon-mask", chance: 0.05 },
    { id: "holy-tao-wheel", chance: 0.05 },
    { id: "kunroon-tear", chance: 0.05 },
    { id: "noble-ring", chance: 0.05 },
    { id: "oma-spirit-ring", chance: 0.05 },
    { id: "poison-ring", chance: 0.05 },
    { id: "power-ring", chance: 0.05 },
    { id: "red-demon-ring", chance: 0.05 },
    { id: "soul-ring", chance: 0.05 },
    { id: "spirit-reformer", chance: 0.05 },
    { id: "violet-orb", chance: 0.05 },
    { id: "bastard-sword", chance: 0.025 },
    { id: "black-tiger-armour", chance: 0.025 },
    { id: "blade-of-sorcery", chance: 0.025 },
    { id: "crane-armour", chance: 0.025 },
    { id: "crimson-ruby-ring", chance: 0.025 },
    { id: "cuspid-necklace", chance: 0.025 },
    { id: "dual-titan-amulet", chance: 0.025 },
    { id: "evil-whisp-amulet", chance: 0.025 },
    { id: "five-element-ring", chance: 0.025 },
    { id: "heaven-sword", chance: 0.0025 },
    { id: "heaven-armour", chance: 0.0025 },
    { id: "lotus-armour", chance: 0.025 },
    { id: "pledge-ring", chance: 0.025 },
    { id: "purified-mirror", chance: 0.025 },
    { id: "sacred-angel-amulet", chance: 0.025 },
    { id: "sorcery-anchor", chance: 0.025 },
    { id: "sword-of-war-god", chance: 0.025 },
    { id: "burst-sword", chance: 0.0125 },
    { id: "conqueror-spear", chance: 0.0125 },
    { id: "dragon-blood-sword", chance: 0.0125 },
    ...bossTopTierStoneDrops(0.03),
    ...bossGemDrops(0.03),
    ...bossOrbDrops(0.01),
  ],
};
const DARK_DEVIL_BOSS_DROPS = {
  gold: 45000,
  benedictionOils: 3,
  items: [
    { id: "awakening-soul", chance: 0.85 },
    { id: "book-flame-field", chance: 0.1 },
    { id: "book-curse", chance: 0.1 },
    { id: "oma-spirit-ring", chance: 0.25 },
    { id: "heaven-sword", chance: 0.008 },
    { id: "heaven-armour", chance: 0.008 },
    { id: "sword-of-war-god", chance: 0.04 },
    { id: "blade-of-sorcery", chance: 0.04 },
    { id: "dragon-slayer", chance: 0.08 },
    { id: "dragon-staff", chance: 0.08 },
    { id: "soul-sabre", chance: 0.08 },
    { id: "judgement-mace", chance: 0.18 },
    { id: "war-mage-staff", chance: 0.18 },
    { id: "soul-spring-wand", chance: 0.18 },
    { id: "war-spirit-blade", chance: 0.18 },
    { id: "magic-scythe", chance: 0.18 },
    { id: "stone-bamboo-fan", chance: 0.18 },
    { id: "steel-armour", chance: 0.12 },
    { id: "dragon-robe", chance: 0.12 },
    { id: "titan-armour", chance: 0.12 },
    { id: "skeleton-helmet", chance: 0.1 },
    { id: "black-iron-helmet", chance: 0.06 },
    { id: "shaman-helmet", chance: 0.06 },
    { id: "brass-helmet", chance: 0.05 },
    { id: "death-gauntlet", chance: 0.06 },
    { id: "claw-necklace", chance: 0.1 },
    { id: "pearl-necklace", chance: 0.1 },
    { id: "life-necklace", chance: 0.1 },
    { id: "spirit-necklace", chance: 0.1 },
    { id: "gale-necklace", chance: 0.08 },
    { id: "green-bead", chance: 0.06 },
    { id: "demonic-bells", chance: 0.06 },
    { id: "soul-necklace", chance: 0.06 },
    { id: "knight-bracelet", chance: 0.08 },
    { id: "soul-spring-bracelet", chance: 0.08 },
    { id: "dragon-bracelet", chance: 0.08 },
    { id: "dragon-ring", chance: 0.1 },
    { id: "ruby-ring", chance: 0.1 },
    { id: "platinum-ring", chance: 0.1 },
    { id: "power-ring", chance: 0.08 },
    { id: "titan-ring", chance: 0.08 },
    { id: "violet-ring", chance: 0.08 },
    { id: "spirit-ring", chance: 0.08 },
    { id: "expel-ring", chance: 0.08 },
    { id: "gale-ring", chance: 0.06 },
    { id: "impact-drug-m", chance: 0.15 },
    { id: "magic-drug-m", chance: 0.15 },
    { id: "taoist-drug-m", chance: 0.15 },
    ...bossTopTierStoneDrops(0.03),
    ...CRYSTAL_ARMOUR_RARE_BOSS_DROPS,
    ...KING_HOG_PREMIUM_DROPS,
    ...bossGemDrops(0.12),
    ...bossOrbDrops(0.025),
  ],
};
const HELL_KEEPER_BOSS_DROPS = {
  gold: 28000,
  benedictionOils: 2,
  items: [
    { id: "awakening-soul", chance: 1 },
    ...bossTopTierStoneDrops(0.03),
    ...bossGemDrops(0.05),
    ...bossOrbDrops(0.01),
  ],
};
const BOSS_DROP_TABLE_BY_LABEL = {
  "Wooma Taurus": WOMA_TAURUS_BOSS_DROPS,
  "Incarnated Wooma Taurus": INCARNATED_WT_BOSS_DROPS,
  "Incarnated Zuma Taurus": INCARNATED_ZT_BOSS_DROPS,
  "Evil Snake": EVIL_SNAKE_BOSS_DROPS,
  "Zuma Taurus": ZUMA_TAURUS_BOSS_DROPS,
  "Evil Centipede": EVIL_CENTIPEDE_BOSS_DROPS,
  "Bone Lord": BONE_LORD_BOSS_DROPS,
  "King Scorpion": KING_SCORPION_BOSS_DROPS,
  "Minotaur King": MINOTAUR_KING_BOSS_DROPS,
  "Yimoogi": YIMOOGI_BOSS_DROPS,
  "Oma King Spirit": OMA_KING_SPIRIT_BOSS_DROPS,
  "King Hog": KING_HOG_BOSS_DROPS,
  "Dream Devourer": RED_CAVERN_DEVOURER_BOSS_DROPS,
  "Dark Devourer": RED_CAVERN_DEVOURER_BOSS_DROPS,
  "Dark Devil": DARK_DEVIL_BOSS_DROPS,
  "Hell Keeper": HELL_KEEPER_BOSS_DROPS,
};

export function clampChance(value) {
  const n = Number(value);
  if (!Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(1, n));
}

/** Returns an array of human-readable problems (empty array means the tables are valid). */
export function validateBossDropTables(tables, knownItemIds = null) {
  const problems = [];
  for (const [label, table] of Object.entries(tables ?? {})) {
    if (!Array.isArray(table?.items) || table.items.length === 0) {
      problems.push(label + ': has no items');
      continue;
    }
    if (!Number.isFinite(Number(table.gold)) || Number(table.gold) < 0) {
      problems.push(label + ': invalid gold ' + table.gold);
    }
    for (const entry of table.items) {
      if (!entry || typeof entry.id !== 'string') {
        problems.push(label + ': an entry is missing its id');
        continue;
      }
      const chance = Number(entry.chance);
      if (!Number.isFinite(chance) || chance <= 0 || chance > 1) {
        problems.push(label + ': ' + entry.id + ' has out-of-range chance ' + entry.chance);
      }
      if (knownItemIds && !knownItemIds.has(entry.id)) {
        problems.push(label + ': ' + entry.id + ' is not a known item id');
      }
    }
  }
  return problems;
}

export {
  BOSS_DROP_TABLE_BY_LABEL,
  BOSS_GEM_ITEM_IDS,
  BOSS_ORB_ITEM_IDS,
};
