export const PHASE1_ENEMY_TEMPLATES = [
  {
    id: 29,
    name: "Chicken",
    crystalName: "Hen",
    level: 2,
    maxHp: 5,
    maxMp: 0,
    dc: [1, 1],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 3,
    agility: 10,
    luck: 0,
    attackMs: 3000,
    moveMs: 1400,
    experience: 9,
    dropPath: "Provinces\\Hen",
    monsterIndex: 3,
  },
  {
    id: 30,
    name: "Deer",
    level: 12,
    maxHp: 25,
    maxMp: 0,
    dc: [2, 4],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 4,
    agility: 7,
    luck: 0,
    attackMs: 3000,
    moveMs: 1400,
    experience: 18,
    dropPath: "Provinces\\Deer",
    monsterIndex: 4,
  },
  {
    id: 39,
    name: "Scarecrow",
    level: 10,
    maxHp: 20,
    maxMp: 0,
    dc: [1, 2],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 5,
    agility: 8,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 15,
    dropPath: "Provinces\\Scarecrow",
    monsterIndex: 5,
  },
  {
    id: 44,
    name: "Raking Cat",
    crystalName: "RakingCat",
    level: 13,
    maxHp: 32,
    maxMp: 0,
    dc: [2, 4],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 5,
    agility: 8,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 27,
    dropPath: "Provinces\\RakingCat",
    monsterIndex: 7,
  },
  {
    id: 42,
    name: "Hooking Cat",
    crystalName: "HookingCat",
    level: 13,
    maxHp: 30,
    maxMp: 0,
    dc: [2, 4],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 5,
    agility: 7,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 23,
    dropPath: "Provinces\\HookingCat",
    monsterIndex: 6,
  },
  {
    id: 37,
    name: "Yob",
    level: 12,
    maxHp: 20,
    maxMp: 0,
    dc: [0, 5],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 6,
    agility: 13,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 20,
    dropPath: "Provinces\\Yob",
    monsterIndex: 8,
  },
  {
    id: 48,
    name: "Oma",
    level: 15,
    maxHp: 30,
    maxMp: 0,
    dc: [4, 9],
    mc: [0, 0],
    sc: [0, 0],
    ac: [1, 1],
    amc: [0, 0],
    accuracy: 6,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 30,
    dropPath: "Provinces\\Oma",
    monsterIndex: 9,
  },
  {
    id: 55,
    name: "Yeti",
    crystalName: "ForestYeti",
    level: 16,
    maxHp: 36,
    maxMp: 0,
    dc: [7, 10],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [0, 0],
    accuracy: 7,
    agility: 12,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 36,
    dropPath: "Provinces\\ForestYeti",
    monsterIndex: 11,
  },
  {
    id: 46,
    name: "Spitting Spider",
    crystalName: "SpittingSpider",
    level: 16,
    maxHp: 65,
    maxMp: 0,
    dc: [6, 9],
    mc: [0, 0],
    sc: [2, 4],
    ac: [2, 2],
    amc: [1, 1],
    accuracy: 8,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 900,
    experience: 108,
    dropPath: "Provinces\\SpittingSpider",
    monsterIndex: 12,
  },
  {
    id: 85,
    name: "Skeleton",
    level: 18,
    maxHp: 90,
    maxMp: 0,
    dc: [7, 10],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 11,
    agility: 13,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 140,
    undead: true,
    dropPath: "BichonProvince\\OmaCave\\Skeleton",
    monsterIndex: 22,
  },
  {
    id: 81,
    name: "Cave Bat",
    crystalName: "CaveBat",
    level: 20,
    maxHp: 25,
    maxMp: 0,
    dc: [4, 6],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [0, 0],
    accuracy: 11,
    agility: 25,
    luck: 0,
    attackMs: 2500,
    moveMs: 1200,
    experience: 34,
    dropPath: "BichonProvince\\OmaCave\\CaveBat",
    monsterIndex: 19,
  },
  {
    id: 83,
    name: "Cave Maggot",
    crystalName: "CaveMaggot",
    level: 31,
    maxHp: 80,
    maxMp: 0,
    dc: [6, 8],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 12,
    agility: 12,
    luck: 0,
    attackMs: 2500,
    moveMs: 1000,
    experience: 122,
    dropPath: "BichonProvince\\OmaCave\\CaveMaggot",
    monsterIndex: 20,
  },
  {
    id: 84,
    name: "Scorpion",
    level: 18,
    maxHp: 45,
    maxMp: 0,
    dc: [7, 16],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [0, 0],
    accuracy: 10,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1200,
    experience: 84,
    dropPath: "BichonProvince\\OmaCave\\Scorpion",
    monsterIndex: 21,
  },
  {
    id: 90,
    name: "Bone Fighter",
    crystalName: "BoneFighter",
    level: 20,
    maxHp: 110,
    maxMp: 0,
    dc: [7, 13],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [1, 1],
    accuracy: 11,
    agility: 13,
    luck: 0,
    attackMs: 2300,
    moveMs: 1200,
    experience: 160,
    undead: true,
    dropPath: "BichonProvince\\OmaCave\\BoneFighter",
    monsterIndex: 23,
  },
  {
    id: 87,
    name: "Axe Skeleton",
    crystalName: "AxeSkeleton",
    level: 18,
    maxHp: 100,
    maxMp: 0,
    dc: [4, 9],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 15,
    agility: 12,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 140,
    undead: true,
    dropPath: "BichonProvince\\OmaCave\\AxeSkeleton",
    monsterIndex: 24,
  },
  {
    id: 92,
    name: "Bone Warrior",
    crystalName: "BoneWarrior",
    level: 19,
    maxHp: 105,
    maxMp: 0,
    dc: [2, 15],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 12,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 180,
    undead: true,
    dropPath: "BichonProvince\\OmaCave\\BoneWarrior",
    monsterIndex: 25,
  },
  {
    id: 94,
    name: "Bone Elite",
    crystalName: "BoneElite",
    level: 20,
    maxHp: 500,
    maxMp: 0,
    dc: [7, 24],
    mc: [0, 0],
    sc: [0, 0],
    ac: [5, 5],
    amc: [4, 4],
    accuracy: 14,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1200,
    experience: 960,
    undead: true,
    dropPath: "BichonProvince\\OmaCave\\BoneElite",
    monsterIndex: 26,
  },
  {
    id: 110,
    name: "Zombie 2",
    crystalName: "Zombie2",
    level: 25,
    maxHp: 155,
    maxMp: 0,
    dc: [12, 16],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 13,
    agility: 13,
    luck: 0,
    attackMs: 3000,
    moveMs: 2000,
    experience: 200,
    undead: true,
    dropPath: "BichonProvince\\DeadMine\\Zombie2",
    monsterIndex: 69,
  },
  {
    id: 112,
    name: "Zombie 3",
    crystalName: "Zombie3",
    level: 12,
    maxHp: 155,
    maxMp: 0,
    dc: [8, 17],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [1, 1],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 3000,
    moveMs: 2000,
    experience: 200,
    undead: true,
    dropPath: "BichonProvince\\DeadMine\\Zombie3",
    monsterIndex: 70,
  },
  {
    id: 114,
    name: "Zombie 4",
    crystalName: "Zombie4",
    level: 25,
    maxHp: 155,
    maxMp: 0,
    dc: [6, 17],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [1, 1],
    accuracy: 12,
    agility: 15,
    luck: 0,
    attackMs: 3000,
    moveMs: 2000,
    experience: 200,
    undead: true,
    dropPath: "BichonProvince\\DeadMine\\Zombie4",
    monsterIndex: 71,
  },
  {
    id: 116,
    name: "Zombie 5",
    crystalName: "Zombie5",
    level: 25,
    maxHp: 155,
    maxMp: 0,
    dc: [6, 17],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [1, 1],
    accuracy: 12,
    agility: 15,
    luck: 0,
    attackMs: 3000,
    moveMs: 2000,
    experience: 200,
    undead: true,
    dropPath: "BichonProvince\\DeadMine\\Zombie5",
    monsterIndex: 72,
  },
  {
    id: 122,
    name: "Priest Zombie",
    crystalName: "PriestZombie",
    level: 25,
    maxHp: 155,
    maxMp: 0,
    dc: [12, 16],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 13,
    agility: 13,
    luck: 0,
    attackMs: 3000,
    moveMs: 2000,
    experience: 200,
    undead: true,
    dropPath: "BichonProvince\\DeadMine\\PriestZombie",
    monsterIndex: 69,
  },
  {
    id: 124,
    name: "Cl Zombie",
    crystalName: "ClZombie",
    level: 12,
    maxHp: 155,
    maxMp: 0,
    dc: [8, 17],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [1, 1],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 3000,
    moveMs: 2000,
    experience: 200,
    undead: true,
    dropPath: "BichonProvince\\DeadMine\\ClZombie",
    monsterIndex: 70,
  },
  {
    id: 126,
    name: "Nd Zombie",
    crystalName: "NdZombie",
    level: 25,
    maxHp: 155,
    maxMp: 0,
    dc: [6, 17],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [1, 1],
    accuracy: 12,
    agility: 15,
    luck: 0,
    attackMs: 3000,
    moveMs: 2000,
    experience: 200,
    undead: true,
    dropPath: "BichonProvince\\DeadMine\\NdZombie",
    monsterIndex: 71,
  },
  {
    id: 128,
    name: "Crawler Zombie",
    crystalName: "CrawlerZombie",
    level: 25,
    maxHp: 155,
    maxMp: 0,
    dc: [6, 17],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [1, 1],
    accuracy: 12,
    agility: 15,
    luck: 0,
    attackMs: 3000,
    moveMs: 2000,
    experience: 200,
    undead: true,
    dropPath: "BichonProvince\\DeadMine\\CrawlerZombie",
    monsterIndex: 72,
  },
  {
    id: 130,
    name: "Shaman Zombie",
    crystalName: "ShamanZombie",
    level: 25,
    maxHp: 155,
    maxMp: 0,
    dc: [6, 17],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [1, 1],
    accuracy: 12,
    agility: 15,
    luck: 0,
    attackMs: 3000,
    moveMs: 1500,
    experience: 210,
    undead: true,
    dropPath: "BichonProvince\\DeadMine\\ShamanZombie",
    monsterIndex: 73,
  },
  {
    id: 118,
    name: "Ghoul",
    level: 25,
    maxHp: 500,
    maxMp: 0,
    dc: [18, 38],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 3],
    amc: [3, 3],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 2800,
    moveMs: 1500,
    experience: 1200,
    dropPath: "BichonProvince\\DeadMine\\Ghoul",
    monsterIndex: 74,
  },
  {
    id: 229,
    name: "Spider Frog",
    crystalName: "SpiderFrog",
    level: 27,
    maxHp: 185,
    maxMp: 0,
    dc: [13, 19],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [2, 2],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 900,
    experience: 220,
    dropPath: "WoomyonWoods\\InsectCave\\SpiderFrog",
    monsterIndex: 81,
  },
  {
    id: 231,
    name: "Horo Blaster",
    crystalName: "HoroBlaster",
    level: 27,
    maxHp: 200,
    maxMp: 0,
    dc: [13, 20],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 3],
    amc: [2, 2],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1200,
    experience: 230,
    dropPath: "WoomyonWoods\\InsectCave\\HoroBlaster",
    monsterIndex: 82,
  },
  {
    id: 233,
    name: "Blue Horo Blaster",
    crystalName: "BlueHoroBlaster",
    level: 26,
    maxHp: 180,
    maxMp: 0,
    dc: [12, 18],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [3, 3],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1200,
    experience: 220,
    dropPath: "WoomyonWoods\\InsectCave\\BlueHoroBlaster",
    monsterIndex: 83,
  },
  {
    id: 235,
    name: "Kek Tal",
    crystalName: "KekTal",
    level: 28,
    maxHp: 190,
    maxMp: 0,
    dc: [14, 20],
    mc: [0, 0],
    sc: [0, 0],
    ac: [4, 4],
    amc: [2, 2],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 1800,
    moveMs: 1200,
    experience: 230,
    dropPath: "WoomyonWoods\\InsectCave\\KekTal",
    monsterIndex: 84,
  },
  {
    id: 237,
    name: "Violet Kek Tal",
    crystalName: "VioletKekTal",
    level: 28,
    maxHp: 190,
    maxMp: 0,
    dc: [14, 20],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 2],
    amc: [4, 4],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 1600,
    moveMs: 900,
    experience: 230,
    dropPath: "WoomyonWoods\\InsectCave\\VioletKekTal",
    monsterIndex: 85,
  },
  {
    id: 239,
    name: "Khazard",
    level: 28,
    maxHp: 2000,
    maxMp: 0,
    dc: [20, 50],
    mc: [0, 0],
    sc: [0, 0],
    ac: [15, 15],
    amc: [10, 10],
    accuracy: 15,
    agility: 16,
    luck: 0,
    attackMs: 1800,
    moveMs: 800,
    experience: 3300,
    dropPath: "WoomyonWoods\\InsectCave\\Khazard",
    monsterIndex: 86,
  },
  {
    id: 240,
    name: "Dark",
    level: 26,
    maxHp: 165,
    maxMp: 0,
    dc: [9, 16],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 3],
    amc: [2, 2],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 900,
    experience: 240,
    dropPath: "WoomyonWoods\\WoomaTemple\\Dark",
    monsterIndex: 28,
  },
  {
    id: 242,
    name: "Dung",
    level: 26,
    maxHp: 155,
    maxMp: 0,
    dc: [9, 17],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 3],
    amc: [2, 2],
    accuracy: 12,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1800,
    experience: 215,
    dropPath: "WoomyonWoods\\WoomaTemple\\Dung",
    monsterIndex: 27,
  },
  {
    id: 244,
    name: "Wooma Soldier",
    crystalName: "WoomaSoldier",
    level: 30,
    maxHp: 285,
    maxMp: 0,
    dc: [16, 28],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 3],
    amc: [2, 2],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1000,
    experience: 310,
    dropPath: "WoomyonWoods\\WoomaTemple\\WoomaSoldier",
    monsterIndex: 29,
  },
  {
    id: 246,
    name: "Wooma Fighter",
    crystalName: "WoomaFighter",
    level: 30,
    maxHp: 285,
    maxMp: 0,
    dc: [16, 28],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 3],
    amc: [2, 2],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1000,
    experience: 340,
    dropPath: "WoomyonWoods\\WoomaTemple\\WoomaFighter",
    monsterIndex: 30,
  },
  {
    id: 248,
    name: "Wooma Warrior",
    crystalName: "WoomaWarrior",
    level: 30,
    maxHp: 285,
    maxMp: 0,
    dc: [15, 28],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 3],
    amc: [2, 2],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1000,
    experience: 340,
    dropPath: "WoomyonWoods\\WoomaTemple\\WoomaWarrior",
    monsterIndex: 31,
  },
  {
    id: 250,
    name: "Flaming Wooma",
    crystalName: "FlamingWooma",
    level: 31,
    maxHp: 240,
    maxMp: 0,
    dc: [14, 26],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 20,
    agility: 20,
    luck: 0,
    attackMs: 1700,
    moveMs: 800,
    experience: 350,
    dropPath: "WoomyonWoods\\WoomaTemple\\FlamingWooma",
    monsterIndex: 32,
    attackDefenceType: "MACAgility",
  },
  {
    id: 253,
    name: "Wooma Guardian",
    crystalName: "WoomaGuardian",
    level: 31,
    maxHp: 1000,
    maxMp: 0,
    dc: [22, 42],
    mc: [0, 0],
    sc: [0, 0],
    ac: [8, 8],
    amc: [8, 8],
    accuracy: 17,
    agility: 20,
    luck: 0,
    attackMs: 1500,
    moveMs: 800,
    experience: 2400,
    dropPath: "WoomyonWoods\\WoomaTemple\\WoomaGuardian",
    monsterIndex: 33,
  },
  {
    id: 256,
    name: "Wooma Taurus",
    crystalName: "WoomaTaurus",
    level: 31,
    maxHp: 3000,
    maxMp: 0,
    dc: [35, 90],
    mc: [0, 0],
    sc: [0, 0],
    ac: [25, 25],
    amc: [40, 40],
    accuracy: 20,
    agility: 30,
    luck: 0,
    attackMs: 2500,
    moveMs: 1800,
    experience: 6000,
    dropPath: "WoomyonWoods\\WoomaTemple\\WoomaTaurus",
    monsterIndex: 34,
    attackDefenceType: "MACAgility",
  },
  {
    id: 150,
    name: "Black Maggot",
    crystalName: "BlackMaggot",
    level: 28,
    maxHp: 200,
    maxMp: 0,
    dc: [10, 15],
    mc: [0, 0],
    sc: [0, 0],
    ac: [5, 5],
    amc: [4, 4],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 1500,
    moveMs: 600,
    experience: 250,
    dropPath: "MongchonProvince\\BugCave\\BlackMaggot",
    monsterIndex: 38,
  },
  {
    id: 152,
    name: "Centipede",
    level: 26,
    maxHp: 210,
    maxMp: 0,
    dc: [12, 18],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1500,
    experience: 310,
    dropPath: "MongchonProvince\\BugCave\\Centipede",
    monsterIndex: 37,
  },
  {
    id: 154,
    name: "Giant Worm",
    crystalName: "GiantWorm",
    level: 26,
    maxHp: 180,
    maxMp: 0,
    dc: [15, 18],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 3],
    amc: [2, 2],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1200,
    experience: 310,
    dropPath: "MongchonProvince\\BugCave\\GiantWorm",
    monsterIndex: 36,
  },
  {
    id: 156,
    name: "Whimpering Bee",
    crystalName: "WhimperingBee",
    level: 26,
    maxHp: 180,
    maxMp: 0,
    dc: [12, 18],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 3],
    amc: [2, 2],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1500,
    experience: 275,
    dropPath: "MongchonProvince\\BugCave\\WhimperingBee",
    monsterIndex: 35,
  },
  {
    id: 158,
    name: "Tongs",
    level: 31,
    maxHp: 240,
    maxMp: 0,
    dc: [15, 25],
    mc: [0, 0],
    sc: [0, 0],
    ac: [5, 5],
    amc: [4, 4],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 1800,
    moveMs: 1500,
    experience: 340,
    dropPath: "MongchonProvince\\BugCave\\Tongs",
    monsterIndex: 39,
  },
  {
    id: 160,
    name: "Evil Tongs",
    crystalName: "EvilTongs",
    level: 38,
    maxHp: 480,
    maxMp: 0,
    dc: [18, 32],
    mc: [0, 0],
    sc: [0, 0],
    ac: [10, 10],
    amc: [7, 7],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 1800,
    moveMs: 900,
    experience: 720,
    dropPath: "MongchonProvince\\BugCave\\EvilTongs",
    monsterIndex: 40,
  },
  {
    id: 166,
    name: "Evil Centipede",
    crystalName: "EvilCentipede",
    level: 99,
    maxHp: 6000,
    maxMp: 0,
    dc: [40, 90],
    mc: [0, 0],
    sc: [5, 15],
    ac: [20, 20],
    amc: [50, 50],
    accuracy: 50,
    agility: 30,
    luck: 0,
    attackMs: 2000,
    moveMs: 2000,
    experience: 6000,
    dropPath: "MongchonProvince\\BugCave\\EvilCentipede",
    monsterIndex: 41,
    fixedArenaSpawn: true,
    spawnAction: "show",
    attackMode: "evilCentipede",
    attackDefenceType: "MAC",
    attackRangeTiles: 7,
    attackImpactDelayMs: 500,
  },
  {
    id: 261,
    name: "Red Boar",
    crystalName: "RedBoar",
    level: 32,
    maxHp: 300,
    maxMp: 0,
    dc: [18, 25],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [8, 8],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1200,
    experience: 500,
    dropPath: "MongchonProvince\\StoneTomb\\RedBoar",
    monsterIndex: 45,
  },
  {
    id: 262,
    name: "Black Boar",
    crystalName: "BlackBoar",
    level: 35,
    maxHp: 280,
    maxMp: 0,
    dc: [20, 26],
    mc: [0, 0],
    sc: [0, 0],
    ac: [10, 10],
    amc: [0, 0],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 800,
    experience: 580,
    dropPath: "MongchonProvince\\StoneTomb\\BlackBoar",
    monsterIndex: 46,
  },
  {
    id: 263,
    name: "Wedge Moth",
    crystalName: "WedgeMoth",
    level: 32,
    maxHp: 220,
    maxMp: 0,
    dc: [8, 14],
    mc: [0, 0],
    sc: [0, 0],
    ac: [1, 2],
    amc: [2, 7],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 600,
    experience: 540,
    dropPath: "MongchonProvince\\StoneTomb\\WedgeMoth",
    monsterIndex: 44,
  },
  {
    id: 264,
    name: "Snake Scorpion",
    crystalName: "SnakeScorpion",
    level: 35,
    maxHp: 330,
    maxMp: 0,
    dc: [22, 28],
    mc: [0, 0],
    sc: [0, 0],
    ac: [5, 5],
    amc: [3, 3],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 600,
    experience: 550,
    dropPath: "MongchonProvince\\StoneTomb\\SnakeScorpion",
    monsterIndex: 47,
  },
  {
    id: 265,
    name: "White Boar",
    crystalName: "WhiteBoar",
    level: 50,
    maxHp: 2000,
    maxMp: 0,
    dc: [30, 55],
    mc: [0, 0],
    sc: [0, 0],
    ac: [15, 15],
    amc: [15, 15],
    accuracy: 17,
    agility: 22,
    luck: 0,
    attackMs: 1800,
    moveMs: 800,
    experience: 3600,
    dropPath: "MongchonProvince\\StoneTomb\\WhiteBoar",
    monsterIndex: 48,
  },
  {
    id: 266,
    name: "Evil Snake",
    crystalName: "EvilSnake",
    level: 50,
    maxHp: 2000,
    maxMp: 0,
    dc: [30, 85],
    mc: [0, 0],
    sc: [0, 0],
    ac: [30, 30],
    amc: [30, 30],
    accuracy: 20,
    agility: 25,
    luck: 0,
    attackMs: 1800,
    moveMs: 600,
    experience: 4800,
    dropPath: "MongchonProvince\\StoneTomb\\EvilSnake",
    monsterIndex: 49,
    attackDefenceType: "ACAgility",
  },
  {
    id: 267,
    name: "Giant Rat",
    crystalName: "GiantRat",
    level: 34,
    maxHp: 1000,
    maxMp: 0,
    dc: [15, 32],
    mc: [0, 0],
    sc: [0, 0],
    ac: [3, 6],
    amc: [0, 0],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1200,
    experience: 1800,
    dropPath: "MongchonProvince\\Zuma\\GiantRat",
    monsterIndex: 63,
  },
  {
    id: 268,
    name: "Zuma Archer",
    crystalName: "ZumaArcher",
    level: 40,
    maxHp: 900,
    maxMp: 0,
    dc: [22, 38],
    mc: [0, 0],
    sc: [0, 0],
    ac: [10, 10],
    amc: [15, 15],
    accuracy: 17,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1000,
    experience: 1900,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaArcher",
    monsterIndex: 64,
    attackMode: "zumaArcher",
    attackDefenceType: "MACAgility",
    rangedAttackDefenceType: "MACAgility",
    attackRangeTiles: 7,
    attackImpactDelayMs: 400,
    rangedAttackExtraMs: 300,
  },
  {
    id: 269,
    name: "Zuma Statue",
    crystalName: "ZumaStatue",
    level: 50,
    maxHp: 1000,
    maxMp: 0,
    dc: [22, 28],
    mc: [0, 0],
    sc: [0, 0],
    ac: [12, 12],
    amc: [15, 15],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2000,
    moveMs: 900,
    experience: 2200,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaStatue",
    monsterIndex: 65,
  },
  {
    id: 270,
    name: "Zuma Guardian",
    crystalName: "ZumaGuardian",
    level: 50,
    maxHp: 1100,
    maxMp: 0,
    dc: [27, 44],
    mc: [0, 0],
    sc: [0, 0],
    ac: [16, 16],
    amc: [16, 16],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2000,
    moveMs: 700,
    experience: 2400,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaGuardian",
    monsterIndex: 66,
  },
  {
    id: 271,
    name: "Red Thunder Zuma",
    crystalName: "RedThunderZuma",
    level: 54,
    maxHp: 3000,
    maxMp: 0,
    dc: [20, 70],
    mc: [0, 0],
    sc: [0, 0],
    ac: [18, 18],
    amc: [20, 20],
    accuracy: 25,
    agility: 22,
    luck: 0,
    attackMs: 1000,
    moveMs: 1000,
    experience: 5000,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\RedThunderZuma",
    monsterIndex: 67,
  },
  {
    id: 272,
    name: "Zuma Taurus",
    crystalName: "ZumaTaurus",
    level: 60,
    maxHp: 12000,
    maxMp: 0,
    dc: [40, 80],
    mc: [0, 0],
    sc: [0, 0],
    ac: [35, 35],
    amc: [30, 30],
    accuracy: 30,
    agility: 32,
    luck: 0,
    attackMs: 1000,
    moveMs: 630,
    experience: 12000,
    dropPath: "MongchonProvince\\Zuma\\ZumaTaurus",
    monsterIndex: 68,
    attackDefenceType: "MACAgility",
  },
  {
    id: 273,
    name: "Toxic Ghoul",
    crystalName: "ToxicGhoul",
    level: 33,
    maxHp: 350,
    maxMp: 0,
    dc: [12, 26],
    mc: [0, 0],
    sc: [0, 0],
    ac: [6, 6],
    amc: [4, 4],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2200,
    moveMs: 1500,
    experience: 940,
    undead: true,
    dropPath: "PranjaIsland\\PranjaStoneCave\\ToxicGhoul",
    monsterIndex: 88,
  },
  {
    id: 274,
    name: "Ronin Ghoul",
    crystalName: "RoninGhoul",
    level: 35,
    maxHp: 430,
    maxMp: 0,
    dc: [14, 30],
    mc: [0, 0],
    sc: [0, 0],
    ac: [6, 6],
    amc: [4, 4],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 1800,
    moveMs: 1000,
    experience: 1020,
    undead: true,
    dropPath: "PranjaIsland\\PranjaStoneCave\\RoninGhoul",
    monsterIndex: 87,
  },
  {
    id: 275,
    name: "Bone Archer",
    crystalName: "BoneArcher",
    level: 38,
    maxHp: 450,
    maxMp: 0,
    dc: [9, 24],
    mc: [0, 0],
    sc: [0, 0],
    ac: [7, 7],
    amc: [5, 5],
    accuracy: 5,
    agility: 8,
    luck: 0,
    attackMs: 2000,
    moveMs: 1200,
    experience: 1020,
    undead: true,
    dropPath: "PranjaIsland\\PranjaStoneCave\\BoneArcher",
    monsterIndex: 92,
  },
  {
    id: 276,
    name: "Bone Spearman",
    crystalName: "BoneSpearman",
    level: 42,
    maxHp: 520,
    maxMp: 0,
    dc: [17, 30],
    mc: [0, 0],
    sc: [0, 0],
    ac: [7, 7],
    amc: [5, 5],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1200,
    experience: 1150,
    undead: true,
    dropPath: "PranjaIsland\\PranjaStoneCave\\BoneSpearman",
    monsterIndex: 90,
  },
  {
    id: 277,
    name: "Bone Blademan",
    crystalName: "BoneBlademan",
    level: 45,
    maxHp: 540,
    maxMp: 0,
    dc: [19, 30],
    mc: [0, 0],
    sc: [0, 0],
    ac: [7, 7],
    amc: [5, 5],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1500,
    experience: 1280,
    undead: true,
    dropPath: "PranjaIsland\\PranjaStoneCave\\BoneBlademan",
    monsterIndex: 91,
  },
  {
    id: 278,
    name: "Bone Captain",
    crystalName: "BoneCaptain",
    level: 49,
    maxHp: 620,
    maxMp: 0,
    dc: [19, 35],
    mc: [0, 0],
    sc: [0, 0],
    ac: [9, 9],
    amc: [6, 6],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 1800,
    moveMs: 800,
    experience: 1350,
    undead: true,
    dropPath: "PranjaIsland\\PranjaStoneCave\\BoneCaptain",
    monsterIndex: 89,
  },
  {
    id: 279,
    name: "Bone Lord",
    crystalName: "BoneLord",
    level: 60,
    maxHp: 10000,
    maxMp: 0,
    dc: [45, 85],
    mc: [0, 0],
    sc: [0, 0],
    ac: [30, 30],
    amc: [30, 30],
    accuracy: 20,
    agility: 22,
    luck: 0,
    attackMs: 1200,
    moveMs: 300,
    experience: 10000,
    dropPath: "PranjaIsland\\PranjaStoneCave\\BoneLord",
    monsterIndex: 93,
    attackMode: "boneLord",
    attackRangeTiles: 7,
    attackImpactDelayMs: 500,
    attackDefenceType: "MACAgility",
  },
  {
    id: 280,
    name: "Minotaur",
    crystalName: "Minotaur",
    level: 42,
    maxHp: 500,
    maxMp: 0,
    dc: [20, 33],
    mc: [0, 0],
    sc: [0, 0],
    ac: [8, 8],
    amc: [16, 16],
    accuracy: 14,
    agility: 14,
    luck: 0,
    attackMs: 2000,
    moveMs: 1100,
    experience: 1380,
    undead: true,
    dropPath: "PranjaIsland\\PranjaTemple\\Minotaur",
    monsterIndex: 361,
  },
  {
    id: 281,
    name: "Ice Minotaur",
    crystalName: "IceMinotaur",
    level: 48,
    maxHp: 630,
    maxMp: 0,
    dc: [22, 35],
    mc: [0, 0],
    sc: [0, 0],
    ac: [11, 11],
    amc: [22, 22],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 1900,
    moveMs: 1300,
    experience: 1480,
    undead: true,
    dropPath: "PranjaIsland\\PranjaTemple\\IceMinotaur",
    monsterIndex: 363,
  },
  {
    id: 282,
    name: "Electric Minotaur",
    crystalName: "ElectricMinotaur",
    level: 48,
    maxHp: 600,
    maxMp: 0,
    dc: [22, 35],
    mc: [0, 0],
    sc: [0, 0],
    ac: [8, 8],
    amc: [16, 16],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 1700,
    moveMs: 1100,
    experience: 1450,
    undead: true,
    dropPath: "PranjaIsland\\PranjaTemple\\ElectricMinotaur",
    monsterIndex: 365,
  },
  {
    id: 283,
    name: "Wind Minotaur",
    crystalName: "WindMinotaur",
    level: 48,
    maxHp: 550,
    maxMp: 0,
    dc: [22, 35],
    mc: [0, 0],
    sc: [0, 0],
    ac: [8, 8],
    amc: [16, 16],
    accuracy: 15,
    agility: 17,
    luck: 0,
    attackMs: 1500,
    moveMs: 600,
    experience: 1450,
    undead: true,
    dropPath: "PranjaIsland\\PranjaTemple\\WindMinotaur",
    monsterIndex: 367,
  },
  {
    id: 284,
    name: "Fire Minotaur",
    crystalName: "FireMinotaur",
    level: 48,
    maxHp: 500,
    maxMp: 0,
    dc: [22, 37],
    mc: [0, 0],
    sc: [0, 0],
    ac: [8, 8],
    amc: [16, 16],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 1900,
    moveMs: 1100,
    experience: 1520,
    undead: true,
    dropPath: "PranjaIsland\\PranjaTemple\\FireMinotaur",
    monsterIndex: 369,
  },
  {
    id: 285,
    name: "Right Guard",
    crystalName: "RightGuard",
    level: 49,
    maxHp: 570,
    maxMp: 0,
    dc: [16, 39],
    mc: [0, 0],
    sc: [0, 0],
    ac: [10, 10],
    amc: [20, 20],
    accuracy: 18,
    agility: 16,
    luck: 0,
    attackMs: 1800,
    moveMs: 1000,
    experience: 1700,
    undead: true,
    dropPath: "PranjaIsland\\PranjaTemple\\RightGuard",
    monsterIndex: 371,
    attackMode: "prajnaGuard",
    attackDefenceType: "MACAgility",
    rangedAttackDefenceType: "MAC",
    attackRangeTiles: 8,
    attackImpactDelayMs: 500,
  },
  {
    id: 286,
    name: "Left Guard",
    crystalName: "LeftGuard",
    level: 49,
    maxHp: 620,
    maxMp: 0,
    dc: [15, 39],
    mc: [0, 0],
    sc: [0, 0],
    ac: [11, 11],
    amc: [22, 22],
    accuracy: 18,
    agility: 16,
    luck: 0,
    attackMs: 1800,
    moveMs: 1000,
    experience: 1700,
    undead: true,
    dropPath: "PranjaIsland\\PranjaTemple\\LeftGuard",
    monsterIndex: 373,
    attackMode: "prajnaGuard",
    attackDefenceType: "MACAgility",
    rangedAttackDefenceType: "MAC",
    attackRangeTiles: 8,
    attackImpactDelayMs: 500,
  },
  {
    id: 287,
    name: "Minotaur King",
    crystalName: "MinotaurKing",
    level: 60,
    maxHp: 15000,
    maxMp: 0,
    dc: [45, 110],
    mc: [85, 100],
    sc: [0, 0],
    ac: [35, 35],
    amc: [35, 35],
    accuracy: 22,
    agility: 22,
    luck: 0,
    attackMs: 1000,
    moveMs: 300,
    experience: 15000,
    undead: false,
    dropPath: "PranjaIsland\\PranjaTemple\\MinotaurKing",
    monsterIndex: 375,
    attackMode: "minotaurKing",
    attackDefenceType: "MACAgility",
    rangedAttackDefenceType: "MAC",
    attackRangeTiles: 6,
    attackImpactDelayMs: 500,
    aoeSplashTiles: 3,
    aoeSplashEvery: 3,
    aoeSplashChance: 0.25,
  },
  {
    id: 288,
    name: "Evil Tongs",
    crystalName: "EvilTongs20",
    level: 50,
    maxHp: 1700,
    maxMp: 0,
    dc: [40, 60],
    mc: [0, 0],
    sc: [0, 0],
    ac: [12, 15],
    amc: [12, 15],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2100,
    moveMs: 1200,
    experience: 3000,
    dropPath: "Castle-Gi\\BDD\\EvilTongs20",
    monsterIndex: 40,
  },
  {
    id: 289,
    name: "Evil Snake",
    crystalName: "EvilSnake20",
    level: 50,
    maxHp: 1700,
    maxMp: 0,
    dc: [40, 60],
    mc: [0, 0],
    sc: [0, 0],
    ac: [12, 15],
    amc: [12, 15],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2100,
    moveMs: 1800,
    experience: 3000,
    dropPath: "Castle-Gi\\BDD\\EvilSnake20",
    monsterIndex: 49,
  },
  {
    id: 291,
    name: "Oma King Spirit",
    crystalName: "OmaKingSpirit",
    level: 60,
    maxHp: 25000,
    maxMp: 0,
    dc: [60, 120],
    mc: [0, 0],
    sc: [0, 0],
    ac: [40, 40],
    amc: [45, 45],
    accuracy: 25,
    agility: 25,
    luck: 0,
    attackMs: 1000,
    moveMs: 300,
    experience: 32000,
    dropPath: "BichonProvince\\OmaCave\\OmaKingSpirit",
    monsterIndex: 126,
    attackDefenceType: "MACAgility",
  },
  {
    id: 292,
    name: "King Scorpion",
    crystalName: "KingScorpion",
    level: 70,
    maxHp: 10000,
    maxMp: 0,
    dc: [45, 85],
    mc: [30, 65],
    sc: [0, 0],
    ac: [30, 30],
    amc: [30, 30],
    accuracy: 25,
    agility: 25,
    luck: 0,
    attackMs: 1000,
    moveMs: 630,
    experience: 12000,
    dropPath: "Castle-Gi\\BDD\\KingScorpion",
    monsterIndex: 75,
    attackMode: "kingScorpion",
    attackRangeTiles: 2,
    attackImpactDelayMs: 300,
    attackDefenceType: "ACAgility",
    rangedAttackDefenceType: "MACAgility",
    enrageHpStages: [0.7, 0.4, 0.15],
    enrageDurationMs: 8000,
    enrageAttackMs: 750,
    enrageMoveMs: 500,
    enrageAlwaysRanged: true,
    enrageAttackRangeTiles: 3,
    enrageFinalAttackRangeTiles: 4,
    enrageLineStepMs: 25,
  },
  {
    id: 293,
    name: "Manectric King",
    crystalName: "ManectricKing",
    level: 60,
    maxHp: 28000,
    maxMp: 0,
    dc: [60, 162],
    mc: [80, 140],
    sc: [0, 0],
    ac: [50, 50],
    amc: [70, 70],
    accuracy: 18,
    agility: 17,
    luck: 0,
    attackMs: 1500,
    moveMs: 2000,
    experience: 20000,
    dropPath: "Unused\\IceHell\\ManectricKing",
    monsterIndex: 229,
    attackMode: "massBurst",
    massBurstStyle: "line",
    attackRangeTiles: 3,
    massBurstHpRatio: 0.2,
    massBurstTiles: 7,
    alwaysAoe: true,
    attackImpactDelayMs: 500,
    attackDefenceType: "ACAgility",
    rangedAttackDefenceType: "MACAgility",
  },
  {
    id: 294,
    name: "Flame Queen",
    crystalName: "FlameQueen",
    level: 70,
    maxHp: 32000,
    maxMp: 0,
    dc: [45, 95],
    mc: [60, 130],
    sc: [0, 0],
    ac: [40, 40],
    amc: [45, 45],
    accuracy: 20,
    agility: 18,
    luck: 0,
    attackMs: 1200,
    moveMs: 1800,
    experience: 24000,
    dropPath: "HellFire\\FlameQueen",
    monsterIndex: 242,
    attackMode: "massBurst",
    massBurstStyle: "boneLord",
    attackRangeTiles: 3,
    massBurstHpRatio: 0.2,
    massBurstTiles: 7,
    alwaysAoe: true,
    attackImpactDelayMs: 500,
    attackDefenceType: "ACAgility",
    rangedAttackDefenceType: "MACAgility",
  },
  {
    id: 295,
    name: "Flaming Mutant",
    crystalName: "FlamingMutant",
    level: 80,
    maxHp: 24000,
    maxMp: 0,
    dc: [40, 85],
    mc: [45, 110],
    sc: [0, 0],
    ac: [35, 35],
    amc: [40, 40],
    accuracy: 22,
    agility: 20,
    luck: 0,
    attackMs: 1400,
    moveMs: 1600,
    experience: 22000,
    dropPath: "BattleSystem\\FlamingMutant",
    monsterIndex: 200,
    attackMode: "flamingMutant",
    attackRangeTiles: 9,
    aoeSplashTiles: 3,
    alwaysAoe: true,
    attackImpactDelayMs: 500,
    attackDefenceType: "ACAgility",
    rangedAttackDefenceType: "MACAgility",
  },
  {
    id: 296,
    name: "Scaly Beast",
    crystalName: "ScalyBeast",
    level: 65,
    maxHp: 20000,
    maxMp: 0,
    dc: [42, 90],
    mc: [0, 0],
    sc: [0, 0],
    ac: [38, 38],
    amc: [32, 32],
    accuracy: 19,
    agility: 18,
    luck: 0,
    attackMs: 1300,
    moveMs: 1700,
    experience: 18000,
    dropPath: "Horned\\ScalyBeast",
    monsterIndex: 345,
    attackMode: "scalyBeast",
    aoeSplashTiles: 2,
    aoeSplashChance: 0.34,
    alwaysAoe: true,
    attackImpactDelayMs: 500,
    attackDefenceType: "MAC",
    stompDefenceType: "ACAgility",
  },
  // Purgatory Hall (zone-bdd-3) variants — +50% AMC, AC, and HP; +100% DC vs solo-dungeon originals; BDD wave only.
  {
    id: 297,
    name: "Ghoul",
    level: 25,
    maxHp: 750,
    maxMp: 0,
    dc: [36, 76],
    mc: [0, 0],
    sc: [0, 0],
    ac: [5, 5],
    amc: [5, 5],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 2800,
    moveMs: 1500,
    experience: 1200,
    dropPath: "BichonProvince\\DeadMine\\Ghoul",
    monsterIndex: 74,
  },
  {
    id: 298,
    name: "Zuma Archer",
    crystalName: "ZumaArcher",
    level: 40,
    maxHp: 1350,
    maxMp: 0,
    dc: [44, 76],
    mc: [0, 0],
    sc: [0, 0],
    ac: [15, 15],
    amc: [23, 23],
    accuracy: 17,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1000,
    experience: 1900,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaArcher",
    monsterIndex: 64,
    attackMode: "zumaArcher",
    attackDefenceType: "MACAgility",
    rangedAttackDefenceType: "MACAgility",
    attackRangeTiles: 7,
    attackImpactDelayMs: 400,
    rangedAttackExtraMs: 300,
  },
  {
    id: 299,
    name: "Red Boar",
    crystalName: "RedBoar",
    level: 32,
    maxHp: 450,
    maxMp: 0,
    dc: [36, 50],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [12, 12],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1200,
    experience: 500,
    dropPath: "MongchonProvince\\StoneTomb\\RedBoar",
    monsterIndex: 45,
  },
  {
    id: 300,
    name: "Zuma Statue",
    crystalName: "ZumaStatue",
    level: 50,
    maxHp: 1500,
    maxMp: 0,
    dc: [44, 56],
    mc: [0, 0],
    sc: [0, 0],
    ac: [18, 18],
    amc: [23, 23],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2000,
    moveMs: 900,
    experience: 2200,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaStatue",
    monsterIndex: 65,
  },
  {
    id: 301,
    name: "Wedge Moth",
    crystalName: "WedgeMoth",
    level: 32,
    maxHp: 330,
    maxMp: 0,
    dc: [16, 28],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 3],
    amc: [3, 11],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 600,
    experience: 540,
    dropPath: "MongchonProvince\\StoneTomb\\WedgeMoth",
    monsterIndex: 44,
  },
  {
    id: 302,
    name: "Black Maggot",
    crystalName: "BlackMaggot",
    level: 28,
    maxHp: 300,
    maxMp: 0,
    dc: [20, 30],
    mc: [0, 0],
    sc: [0, 0],
    ac: [8, 8],
    amc: [6, 6],
    accuracy: 13,
    agility: 15,
    luck: 0,
    attackMs: 1500,
    moveMs: 600,
    experience: 250,
    dropPath: "MongchonProvince\\BugCave\\BlackMaggot",
    monsterIndex: 38,
  },
  {
    id: 303,
    name: "Ghoul",
    crystalName: "Ghoul21",
    level: 50,
    maxHp: 1700,
    maxMp: 0,
    dc: [40, 60],
    mc: [0, 0],
    sc: [0, 0],
    ac: [12, 15],
    amc: [12, 15],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2100,
    moveMs: 1800,
    experience: 2900,
    dropPath: "Castle-Gi\\BDD\\Ghoul21",
    monsterIndex: 74,
  },
  {
    id: 304,
    name: "Zuma Archer",
    crystalName: "ZumaArcher21",
    level: 47,
    maxHp: 2500,
    maxMp: 0,
    dc: [50, 100],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 19,
    agility: 19,
    luck: 0,
    attackMs: 1300,
    moveMs: 1800,
    experience: 3100,
    undead: true,
    dropPath: "Castle-Gi\\BDD\\ZumaArcher21",
    monsterIndex: 64,
    attackMode: "zumaArcher",
    attackDefenceType: "MACAgility",
    rangedAttackDefenceType: "MACAgility",
    attackRangeTiles: 7,
    attackImpactDelayMs: 400,
    rangedAttackExtraMs: 300,
  },
  {
    id: 305,
    name: "Wooma Guardian",
    crystalName: "WoomaGuardian6",
    level: 50,
    maxHp: 2000,
    maxMp: 0,
    dc: [50, 110],
    mc: [0, 0],
    sc: [0, 0],
    ac: [10, 22],
    amc: [14, 17],
    accuracy: 20,
    agility: 20,
    luck: 0,
    attackMs: 1800,
    moveMs: 1200,
    experience: 3000,
    dropPath: "Castle-Gi\\BDD\\WoomaGuardian6",
    monsterIndex: 33,
  },
  {
    id: 306,
    name: "Incarnated Wooma Taurus",
    crystalName: "IncarnatedWT",
    level: 60,
    maxHp: 12000,
    maxMp: 0,
    dc: [40, 80],
    mc: [0, 0],
    sc: [0, 0],
    ac: [35, 35],
    amc: [30, 30],
    accuracy: 30,
    agility: 32,
    luck: 0,
    attackMs: 1000,
    moveMs: 630,
    experience: 12000,
    dropPath: "Castle-Gi\\BDD\\IncarnatedWT",
    monsterIndex: 34,
    attackDefenceType: "MACAgility",
    enrageHpStages: [0.7, 0.4, 0.15],
    enrageDurationMs: 8000,
    enrageAttackMs: 600,
  },
  {
    id: 317,
    name: "Incarnated Zuma Taurus",
    crystalName: "IncarnatedZT",
    level: 60,
    maxHp: 20000,
    maxMp: 0,
    dc: [30, 75],
    mc: [0, 0],
    sc: [0, 0],
    ac: [40, 40],
    amc: [45, 45],
    accuracy: 30,
    agility: 32,
    luck: 0,
    attackMs: 1000,
    moveMs: 630,
    experience: 12000,
    dropPath: "Castle-Gi\\BDD\\IncarnatedZT",
    monsterIndex: 68,
    attackDefenceType: "MACAgility",
    enrageHpStages: [0.7, 0.4, 0.15],
    enrageDurationMs: 8000,
    enrageAttackMs: 600,
  },
  {
    id: 318,
    name: "Incarnated Red Thunder Zuma",
    crystalName: "RedThunderZuma",
    level: 58,
    maxHp: 4500,
    maxMp: 0,
    dc: [50, 150],
    meleeDc: [50, 150],
    rangedDc: [100, 250],
    mc: [0, 0],
    sc: [0, 0],
    ac: [27, 27],
    amc: [30, 30],
    accuracy: 25,
    agility: 22,
    luck: 0,
    attackMs: 1000,
    moveMs: 1000,
    experience: 7500,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\RedThunderZuma",
    monsterIndex: 67,
    attackMode: "redThunderZuma",
    attackDefenceType: "MACAgility",
    rangedAttackDefenceType: "MAC",
    attackRangeTiles: 9,
    attackImpactDelayMs: 500,
    rangedAttackExtraMs: 500,
    enrageHpStages: [0.7, 0.4, 0.15],
    enrageDurationMs: 8000,
    enrageAttackMs: 600,
  },
  {
    id: 319,
    name: "Dark Devil",
    crystalName: "DarkDevil",
    level: 70,
    maxHp: 40000,
    maxMp: 0,
    dc: [75, 200],
    mc: [0, 0],
    sc: [0, 0],
    ac: [55, 55],
    amc: [60, 60],
    accuracy: 28,
    agility: 35,
    luck: 0,
    attackMs: 1000,
    moveMs: 630,
    experience: 30000,
    dropPath: "Castle-Gi\\BDD\\DarkDevil",
    monsterIndex: 77,
    attackMode: "darkDevil",
    attackDefenceType: "ACAgility",
    rangedAttackDefenceType: "MACAgility",
    attackRangeTiles: 3,
    darkDevilMeleeRangeTiles: 1,
    darkDevilRangeCooldownMinMs: 2000,
    darkDevilRangeCooldownMaxMs: 5000,
    darkDevilEnrageRangeCooldownMinMs: 800,
    darkDevilEnrageRangeCooldownMaxMs: 1800,
    darkDevilRangeDamageMultiplier: 3,
    attackImpactDelayMs: 500,
    aoeSplashTiles: 2,
    enrageHpStages: [0.7, 0.4, 0.15],
    enrageDurationMs: 8000,
    enrageAttackMs: 600,
    enrageMoveMs: 500,
    enrageAlwaysRanged: true,
  },
  // Wooma Palace North (zone-bdd-5) variants — +50% AMC, AC, and HP; +100% DC vs solo-dungeon originals; BDD wave only.
  {
    id: 307,
    name: "Zuma Statue",
    crystalName: "ZumaStatue",
    level: 50,
    maxHp: 1500,
    maxMp: 0,
    dc: [44, 56],
    mc: [0, 0],
    sc: [0, 0],
    ac: [18, 18],
    amc: [23, 23],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2000,
    moveMs: 900,
    experience: 2200,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaStatue",
    monsterIndex: 65,
  },
  {
    id: 308,
    name: "Zuma Guardian",
    crystalName: "ZumaGuardian",
    level: 50,
    maxHp: 1650,
    maxMp: 0,
    dc: [54, 88],
    mc: [0, 0],
    sc: [0, 0],
    ac: [24, 24],
    amc: [24, 24],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2000,
    moveMs: 700,
    experience: 2400,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaGuardian",
    monsterIndex: 66,
  },
  // HwanMaJin (zone-bdd-6) variants — +50% AMC, AC, and HP; +100% DC vs solo-dungeon originals; BDD wave only.
  {
    id: 309,
    name: "Zuma Archer",
    crystalName: "ZumaArcher20",
    level: 40,
    maxHp: 1350,
    maxMp: 0,
    dc: [44, 76],
    mc: [0, 0],
    sc: [0, 0],
    ac: [15, 15],
    amc: [23, 23],
    accuracy: 17,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1000,
    experience: 1900,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaArcher",
    monsterIndex: 64,
    attackMode: "zumaArcher",
    attackDefenceType: "MACAgility",
    rangedAttackDefenceType: "MACAgility",
    attackRangeTiles: 7,
    attackImpactDelayMs: 400,
    rangedAttackExtraMs: 300,
  },
  {
    id: 310,
    name: "Zuma Statue",
    crystalName: "ZumaStatue20",
    level: 50,
    maxHp: 1500,
    maxMp: 0,
    dc: [44, 56],
    mc: [0, 0],
    sc: [0, 0],
    ac: [18, 18],
    amc: [23, 23],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2000,
    moveMs: 900,
    experience: 2200,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaStatue",
    monsterIndex: 65,
  },
  {
    id: 311,
    name: "Zuma Guardian",
    crystalName: "ZumaGuardian20",
    level: 50,
    maxHp: 1650,
    maxMp: 0,
    dc: [54, 88],
    mc: [0, 0],
    sc: [0, 0],
    ac: [24, 24],
    amc: [24, 24],
    accuracy: 17,
    agility: 17,
    luck: 0,
    attackMs: 2000,
    moveMs: 700,
    experience: 2400,
    undead: true,
    dropPath: "MongchonProvince\\Zuma\\ZumaGuardian",
    monsterIndex: 66,
  },
  {
    id: 312,
    name: "White Boar",
    crystalName: "WhiteBoar20",
    level: 50,
    maxHp: 3000,
    maxMp: 0,
    dc: [60, 110],
    mc: [0, 0],
    sc: [0, 0],
    ac: [23, 23],
    amc: [23, 23],
    accuracy: 17,
    agility: 22,
    luck: 0,
    attackMs: 1800,
    moveMs: 800,
    experience: 3600,
    dropPath: "MongchonProvince\\StoneTomb\\WhiteBoar",
    monsterIndex: 48,
  },
  {
    id: 313,
    name: "Wedge Moth",
    crystalName: "WedgeMoth",
    level: 32,
    maxHp: 330,
    maxMp: 0,
    dc: [16, 28],
    mc: [0, 0],
    sc: [0, 0],
    ac: [2, 3],
    amc: [3, 11],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 600,
    experience: 540,
    dropPath: "MongchonProvince\\StoneTomb\\WedgeMoth",
    monsterIndex: 44,
  },
  {
    id: 316,
    name: "King Hog",
    crystalName: "KingHog",
    level: 60,
    maxHp: 30000,
    maxMp: 0,
    dc: [60, 260],
    mc: [0, 0],
    sc: [0, 0],
    ac: [45, 45],
    amc: [50, 50],
    accuracy: 25,
    agility: 25,
    luck: 0,
    attackMs: 1000,
    moveMs: 1000,
    experience: 18000,
    dropPath: "Castle-Gi\\BDD\\KingHog",
    monsterIndex: 76,
    attackDefenceType: "ACAgility",
  },
  {
    id: 315,
    name: "Ghoul",
    crystalName: "Ghoul20",
    level: 25,
    maxHp: 750,
    maxMp: 0,
    dc: [36, 76],
    mc: [0, 0],
    sc: [0, 0],
    ac: [5, 5],
    amc: [5, 5],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 2800,
    moveMs: 1500,
    experience: 1200,
    dropPath: "BichonProvince\\DeadMine\\Ghoul",
    monsterIndex: 74,
  },
  {
    id: 410,
    name: "Red Snake",
    crystalName: "RedSnake",
    level: 17,
    maxHp: 60,
    maxMp: 0,
    dc: [7, 12],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [2, 2],
    accuracy: 11,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1200,
    experience: 70,
    dropPath: "Provinces\\RedSnake",
    monsterIndex: 111,
  },
  {
    id: 411,
    name: "Tiger Snake",
    crystalName: "TigerSnake",
    level: 17,
    maxHp: 60,
    maxMp: 0,
    dc: [10, 11],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [2, 2],
    accuracy: 12,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1200,
    experience: 98,
    dropPath: "Provinces\\TigerSnake",
    monsterIndex: 112,
  },
  {
    id: 412,
    name: "Blue Viper",
    crystalName: "BlueViper",
    level: 55,
    maxHp: 1100,
    maxMp: 0,
    dc: [44, 52],
    mc: [0, 0],
    sc: [0, 0],
    ac: [7, 7],
    amc: [10, 10],
    accuracy: 16,
    agility: 16,
    luck: 0,
    attackMs: 1700,
    moveMs: 1700,
    experience: 2423,
    dropPath: "SerpantValley\\ViperCave\\BlueViper",
    monsterIndex: 115,
  },
  {
    id: 413,
    name: "Yellow Viper",
    crystalName: "YellowViper",
    level: 55,
    maxHp: 1100,
    maxMp: 0,
    dc: [44, 52],
    mc: [0, 0],
    sc: [0, 0],
    ac: [11, 11],
    amc: [15, 15],
    accuracy: 16,
    agility: 16,
    luck: 0,
    attackMs: 1700,
    moveMs: 1700,
    experience: 2513,
    dropPath: "SerpantValley\\ViperCave\\YellowViper",
    monsterIndex: 116,
  },
  {
    id: 415,
    name: "Guardian Viper",
    crystalName: "GuardianViper",
    level: 55,
    maxHp: 3000,
    maxMp: 0,
    dc: [15, 45],
    mc: [0, 0],
    sc: [0, 0],
    ac: [10, 10],
    amc: [15, 15],
    accuracy: 16,
    agility: 16,
    luck: 0,
    attackMs: 1900,
    moveMs: 1700,
    experience: 5385,
    dropPath: "SerpantValley\\ViperCave\\GuardianViper",
    monsterIndex: 114,
  },
  {
    id: 416,
    name: "Evil Spider",
    crystalName: "EvilSpider",
    level: 65,
    maxHp: 1800,
    maxMp: 0,
    dc: [25, 50],
    mc: [0, 0],
    sc: [0, 0],
    ac: [12, 12],
    amc: [15, 15],
    accuracy: 17,
    agility: 15,
    luck: 0,
    attackMs: 2000,
    moveMs: 1000,
    experience: 4500,
    dropPath: "SerpantValley\\ViperCave\\EvilSpider",
    monsterIndex: 61,
  },
  {
    id: 417,
    name: "Evil Hog",
    crystalName: "EvilHog",
    level: 65,
    maxHp: 1800,
    maxMp: 0,
    dc: [25, 50],
    mc: [0, 0],
    sc: [0, 0],
    ac: [12, 12],
    amc: [15, 15],
    accuracy: 15,
    agility: 17,
    luck: 0,
    attackMs: 2000,
    moveMs: 1000,
    experience: 10000,
    dropPath: "SerpantValley\\ViperCave\\EvilHog",
    monsterIndex: 76,
  },
  {
    id: 414,
    name: "Yimoogi",
    crystalName: "Yimoogi",
    level: 70,
    maxHp: 20000,
    maxMp: 0,
    dc: [70, 130],
    mc: [0, 0],
    sc: [0, 0],
    ac: [40, 40],
    amc: [45, 45],
    accuracy: 25,
    agility: 25,
    luck: 0,
    attackMs: 800,
    moveMs: 600,
    experience: 20000,
    dropPath: "SerpantValley\\ViperCave\\Yimoogi",
    monsterIndex: 113,
    attackDefenceType: "MACAgility",
  },
  {
    id: 290,
    name: "Trainer",
    crystalName: "Trainer",
    level: 99,
    maxHp: 9999,
    maxMp: 0,
    dc: [1, 1],
    mc: [0, 0],
    sc: [0, 0],
    ac: [0, 0],
    amc: [0, 0],
    accuracy: 15,
    agility: 15,
    luck: 0,
    attackMs: 2500,
    moveMs: 1200,
    experience: 0,
    dropPath: "Misc\\Trainer",
    monsterIndex: 140,
    trainingDummy: true,
  },
  {
    id: 901,
    name: "Lab Stone Colossus",
    crystalName: "Mir3StoneColossus",
    level: 45,
    maxHp: 4500,
    maxMp: 0,
    dc: [35, 58],
    mc: [0, 0],
    sc: [0, 0],
    ac: [24, 24],
    amc: [18, 18],
    accuracy: 18,
    agility: 12,
    luck: 0,
    attackMs: 1800,
    moveMs: 1800,
    experience: 9000,
    dropPath: "NewContent\\Mir3StoneColossus",
    monsterIndex: 901,
  },
  {
    id: 902,
    name: "Lab Overseer",
    crystalName: "KillmasterOverseer",
    level: 48,
    maxHp: 5200,
    maxMp: 0,
    dc: [38, 64],
    mc: [0, 0],
    sc: [0, 0],
    ac: [25, 25],
    amc: [20, 20],
    accuracy: 18,
    agility: 14,
    luck: 0,
    attackMs: 1600,
    moveMs: 1500,
    experience: 10000,
    dropPath: "NewContent\\KillmasterOverseer",
    monsterIndex: 902,
  },
  {
    id: 903,
    name: "Lab Halberd Lord",
    crystalName: "Mon51HalberdLord",
    level: 52,
    maxHp: 7800,
    maxMp: 0,
    dc: [45, 76],
    mc: [0, 0],
    sc: [0, 0],
    ac: [30, 30],
    amc: [24, 24],
    accuracy: 20,
    agility: 15,
    luck: 0,
    attackMs: 1500,
    moveMs: 1500,
    experience: 12500,
    dropPath: "NewContent\\Mon51HalberdLord",
    monsterIndex: 903,
  },
  {
    id: 904,
    name: "Lab White Boar",
    crystalName: "NewMagicBeast",
    level: 42,
    maxHp: 3600,
    maxMp: 0,
    dc: [30, 52],
    mc: [0, 0],
    sc: [0, 0],
    ac: [20, 20],
    amc: [16, 16],
    accuracy: 17,
    agility: 16,
    luck: 0,
    attackMs: 1600,
    moveMs: 1400,
    experience: 7600,
    dropPath: "NewContent\\NewMagicBeast",
    monsterIndex: 904,
  },
];

const OMA_CAVE_TILE_PATTERN = [
  [0, 2, 4, 1, 3, 0, 2, 1, 4, 3, 0, 2],
  [3, 1, 4, 2, 0, 1, 3, 4, 2, 0, 1, 4],
  [1, 0, 2, 3, 1, 4, 0, 2, 3, 1, 4, 0],
  [4, 2, 0, 1, 3, 2, 4, 0, 1, 3, 2, 0],
  [2, 4, 3, 0, 1, 4, 2, 3, 0, 1, 4, 2],
];

const OMA_CAVE_KINGS_ROOM_TILE_PATTERN = [
  [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1],
  [3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
  [4, 3, 2, 1, 0, 4, 3, 2, 1, 0, 4, 3],
  [2, 1, 0, 4, 3, 2, 1, 0, 4, 3, 2, 1],
  [2, 4, 1, 3, 0, 4, 2, 0, 3, 1, 2, 4],
];

const OMA_CAVE_OBJECT_PATTERN = [
  Array(24).fill(-1),
  Array(24).fill(-1),
  Array(24).fill(-1),
];

const OMA_CAVE_VISUALS = {
  mapSet: "oma-cave",
  backdrop: "cave",
  edgeSet: "oma-cave-selected",
  decorations: [],
  objectSet: "oma-cave-walls",
  objectPattern: OMA_CAVE_OBJECT_PATTERN,
};

// Crystal D606: respawn at 83,168 (monsterIndex 164). Stamp focus stays on that cell.
// Tall front objects south of spawn (e.g. 5:2529 on row 169) draw over the boss body;
// same-row pit lips draw behind the boss, matching Crystal row-interleaved z-order.
const BUG_CAVE_KINGS_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "evil-centipede-kr-center",
  mapStampOnly: true,
};

// Crystal DM002 KingsTomb — full map stamp; player focus on lower floor near cave entrance.
const KINGS_TOMB_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "kings-tomb-center",
  mapStampOnly: true,
  mapLightning: true,
  mapLightningDamageMin: 50,
  mapLightningDamageMax: 150,
};

const WOOMA_TEMPLE_TILE_PATTERN = [
  [0, 1, 2, 3, 4, 1, 0, 2, 4, 3, 1, 0],
  [3, 4, 1, 0, 2, 4, 3, 1, 0, 2, 4, 3],
  [2, 0, 3, 4, 1, 0, 2, 3, 1, 4, 0, 2],
  [1, 3, 4, 2, 0, 3, 1, 4, 2, 0, 3, 1],
  [4, 2, 0, 1, 3, 2, 4, 0, 1, 3, 2, 4],
];

const WOOMA_TEMPLE_KINGS_ROOM_TILE_PATTERN = [
  [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1],
  [2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3],
  [4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0],
  [1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2],
  [3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
];

const WOOMA_TEMPLE_DECORATIONS = [
  { id: "wooma-group-3-pillar-a", slots: [0], groups: [3], worldX: 320, row: -1.15, repeatEvery: 980 },
  { id: "wooma-group-5-torch-a", slots: [2], groups: [5], worldX: 620, row: -2.85, repeatEvery: 980 },
  { id: "wooma-group-4-skeleton-a", slots: [1], groups: [4], worldX: 900, row: 1.25, repeatEvery: 1260 },
  { id: "wooma-group-6-bones-a", slots: [3], groups: [6], worldX: 1180, row: 1.35, repeatEvery: 1260 },
  { id: "wooma-group-7-stone-a", slots: [4], groups: [7], worldX: 1500, row: 1.1, repeatEvery: 1380 },
];

const WOOMA_TEMPLE_BOSS_DECORATIONS = [
  { id: "wooma-group-3-pillar-kr-a", slots: [0], groups: [3], worldX: 260, row: -1.15, repeatEvery: 760 },
  { id: "wooma-group-5-torch-kr-a", slots: [2], groups: [5], worldX: 480, row: -2.85, repeatEvery: 760 },
  { id: "wooma-group-3-pillar-kr-b", slots: [0], groups: [3], worldX: 700, row: -1.15, repeatEvery: 760 },
  { id: "wooma-group-4-skeleton-kr-a", slots: [1], groups: [4], worldX: 950, row: 1.25, repeatEvery: 1040 },
  { id: "wooma-group-6-bones-kr-a", slots: [3], groups: [6], worldX: 1190, row: 1.35, repeatEvery: 1040 },
  { id: "wooma-group-7-stone-kr-a", slots: [4], groups: [7], worldX: 1420, row: 1.1, repeatEvery: 1040 },
];

const WOOMA_TEMPLE_VISUALS = {
  mapSet: "wooma-temple",
  backdrop: "cave",
  groundTopRows: 6,
  decorationSet: "wooma-temple-picked-groups",
  decorations: WOOMA_TEMPLE_DECORATIONS,
  objectPattern: [],
};

const WOOMA_TEMPLE_KINGS_ROOM_VISUALS = {
  ...WOOMA_TEMPLE_VISUALS,
  decorations: [],
  mapStamp: "wooma-kr-center",
};

// Slots 0-4 = Tiles.Lib frames 2500-2504 (only set that renders solid floor in our pipeline).
const TRAINING_ROOM_VISUALS = {
  mapStamp: "academy-0110-center",
  mapStampOnly: true,
  backdrop: "field",
  decorations: [],
  objectPattern: [],
};

const STONE_TEMPLE_TILE_PATTERN = [
  [0, 2, 4, 1, 3, 0, 2, 4, 1, 3, 0, 2],
  [3, 1, 0, 4, 2, 3, 1, 0, 4, 2, 3, 1],
  [2, 4, 3, 0, 1, 2, 4, 3, 0, 1, 2, 4],
  [1, 0, 2, 3, 4, 1, 0, 2, 3, 4, 1, 0],
  [4, 3, 1, 2, 0, 4, 3, 1, 2, 0, 4, 3],
  [0, 1, 3, 4, 2, 0, 1, 3, 4, 2, 0, 1],
];

// Staggered spacing (uneven repeat/worldX) so props rarely line up; small props sit
// slightly higher than before (row <= prior values — never lower on screen).
const STONE_TEMPLE_DECORATIONS = [
  { id: "st-catalog-65", slots: [0], worldX: 180, row: 0.12, repeatEvery: 2230 },
  { id: "st-catalog-122", slots: [1], worldX: 1320, row: -0.05, repeatEvery: 3070 },
  { id: "st-motif-13-arch", slots: [2], worldX: 760, row: -1.2, repeatEvery: 4010 },
  { id: "st-catalog-86", slots: [3], worldX: 2540, row: -0.14, repeatEvery: 5190 },
];

const STONE_TEMPLE_VISUALS = {
  mapSet: "stone-temple",
  backdrop: "cave",
  groundTopRows: 6,
  decorationSet: "stone-temple-catalog",
  decorations: STONE_TEMPLE_DECORATIONS,
  objectPattern: [],
};

const STONE_TEMPLE_KINGS_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "stone-tomb-kr-center",
  mapStampOnly: true,
};

const VIPER_CAVE_VISUALS = {
  mapSet: "stone-temple",
  backdrop: "cave",
  groundTopRows: 6,
  decorationSet: "stone-temple-catalog",
  decorations: STONE_TEMPLE_DECORATIONS,
  objectPattern: [],
};

const VIPER_CAVE_KINGS_ROOM_VISUALS = {
  ...VIPER_CAVE_VISUALS,
  decorations: [],
  arenaLaneY: 0.82,
};

const ZUMA_TEMPLE_TILE_PATTERN = [
  [0, 2, 4, 1, 3, 0, 2, 4, 1, 3, 0, 2],
  [3, 1, 0, 4, 2, 3, 1, 0, 4, 2, 3, 1],
  [2, 4, 3, 0, 1, 2, 4, 3, 0, 1, 2, 4],
  [1, 0, 2, 3, 4, 1, 0, 2, 3, 4, 1, 0],
  [4, 3, 1, 2, 0, 4, 3, 1, 2, 0, 4, 3],
  [0, 1, 3, 4, 2, 0, 1, 3, 4, 2, 0, 1],
];

// Shared repeat period keeps horizontal spacing fixed while scrolling (no vertical pile-ups).
const ZUMA_DECOR_PERIOD = 3200;
const ZUMA_TEMPLE_DECORATIONS = [
  { id: "zt-catalog-63", slots: [0], worldX: 200, row: -1.22, repeatEvery: ZUMA_DECOR_PERIOD },
  { id: "zt-catalog-5", slots: [4], worldX: 600, row: -1.05, repeatEvery: ZUMA_DECOR_PERIOD },
  { id: "zt-catalog-41", slots: [3], worldX: 1000, row: -0.88, repeatEvery: ZUMA_DECOR_PERIOD },
  { id: "zt-catalog-61", slots: [1], worldX: 1400, row: -0.42, repeatEvery: ZUMA_DECOR_PERIOD },
  { id: "zt-catalog-47", slots: [2], worldX: 1800, row: -0.65, repeatEvery: ZUMA_DECOR_PERIOD },
  { id: "zt-catalog-10", slots: [7], worldX: 2200, row: -0.2, repeatEvery: ZUMA_DECOR_PERIOD },
  { id: "zt-catalog-1", slots: [6], worldX: 2600, row: 0.08, repeatEvery: ZUMA_DECOR_PERIOD },
  { id: "zt-catalog-6", slots: [5], worldX: 3000, row: -0.95, repeatEvery: ZUMA_DECOR_PERIOD },
];

const ZUMA_TEMPLE_VISUALS = {
  mapSet: "zuma-temple",
  backdrop: "cave",
  groundTopRows: 6,
  decorationSet: "zuma-temple-catalog",
  decorations: ZUMA_TEMPLE_DECORATIONS,
  objectPattern: [],
};

const ZUMA_TEMPLE_KINGS_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "zuma-temple-kr-center",
  mapStampOnly: true,
};

// Crystal D2061/D2062 walkable floor: Tiles.Lib 3051-3055 (1950-1954 are black in our export).
const PRAJNA_CAVE_TILE_PATTERN = [
  [0, 2, 4, 1, 3, 0, 2, 1, 4, 3, 0, 2],
  [3, 1, 4, 2, 0, 1, 3, 4, 2, 0, 1, 4],
  [1, 0, 2, 3, 1, 4, 0, 2, 3, 1, 4, 0],
  [4, 2, 0, 1, 3, 2, 4, 0, 1, 3, 2, 0],
  [2, 4, 3, 0, 1, 4, 2, 3, 0, 1, 4, 2],
];

const PRAJNA_CAVE_DECOR_PERIOD = 4000;
// Negative = higher on screen. Each spawn picks one row from this pool (not tied to prop type).
const PRAJNA_CAVE_DECOR_ROWS = [-4.2, -3.4, -3.0, -2.6, -2.1, -1.6, -1.2, -0.8, 0.45, 0.75, 1.05, 1.35];
const PRAJNA_CAVE_DECORATIONS = [
  // Sheet slots 0-11: #22 #33 #37 #39 #40 #41 #42 #43 #45 #72 #77 #78
  { id: "pc-catalog-22", slots: [0], worldX: 180, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-33", slots: [1], worldX: 500, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-37", slots: [2], worldX: 820, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-39", slots: [3], worldX: 1140, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-40", slots: [4], worldX: 1460, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-41", slots: [5], worldX: 1780, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-42", slots: [6], worldX: 2100, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-43", slots: [7], worldX: 2420, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-45", slots: [8], worldX: 2740, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-72", slots: [9], worldX: 3060, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-77", slots: [10], worldX: 3380, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
  { id: "pc-catalog-78", slots: [11], worldX: 3700, repeatEvery: PRAJNA_CAVE_DECOR_PERIOD },
];

const PRAJNA_CAVE_VISUALS = {
  mapSet: "prajna-cave",
  backdrop: "cave",
  groundTopRows: 14,
  stageMinWidth: 760,
  stageMinHeight: 480,
  stageMaxHeight: 540,
  decorationSet: "prajna-cave-catalog",
  decorationRows: PRAJNA_CAVE_DECOR_ROWS,
  decorations: PRAJNA_CAVE_DECORATIONS,
  objectPattern: [],
};

const PRAJNA_CAVE_KINGS_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "prajna-cave-kr-center",
  mapStampOnly: true,
};

// Crystal D2071 walkable floor: Tiles.Lib 3100-3104 (1950-1954 export black).
// Anchor pattern from D2071 (one slot per 2x2 back-tile block at even map rows); use with tileAnchor2x2.
const PRAJNA_TEMPLE_TILE_PATTERN = [
  [2, 1, 4, 4, 2, 3, 4, 1],
  [3, 2, 3, 0, 2, 2, 2, 4],
  [2, 0, 1, 0, 3, 3, 3, 1],
  [3, 0, 2, 3, 3, 2, 4, 2],
  [3, 1, 1, 3, 1, 0, 0, 1],
  [0, 2, 1, 0, 1, 1, 3, 1],
];

const PRAJNA_TEMPLE_DECOR_PERIOD = 4000;
const PRAJNA_TEMPLE_DECORATIONS = [
  { id: "pt-catalog-30", slots: [0], worldX: 200, row: -0.55, repeatEvery: PRAJNA_TEMPLE_DECOR_PERIOD },
  { id: "pt-catalog-36", slots: [1], worldX: 640, row: -0.55, repeatEvery: PRAJNA_TEMPLE_DECOR_PERIOD },
  { id: "pt-catalog-38", slots: [2], worldX: 1080, row: -0.55, repeatEvery: PRAJNA_TEMPLE_DECOR_PERIOD },
  { id: "pt-catalog-45", slots: [3], worldX: 1520, row: -0.95, repeatEvery: PRAJNA_TEMPLE_DECOR_PERIOD },
  { id: "pt-catalog-48", slots: [4], worldX: 1960, row: -0.95, repeatEvery: PRAJNA_TEMPLE_DECOR_PERIOD },
  { id: "pt-catalog-75", slots: [5], worldX: 2400, row: -0.8, repeatEvery: PRAJNA_TEMPLE_DECOR_PERIOD },
  { id: "pt-catalog-76", slots: [6], worldX: 2840, row: -0.8, repeatEvery: PRAJNA_TEMPLE_DECOR_PERIOD },
  { id: "pt-catalog-87", slots: [7], worldX: 3280, row: -1.5, repeatEvery: PRAJNA_TEMPLE_DECOR_PERIOD },
  { id: "pt-catalog-102", slots: [8], worldX: 3720, row: -1.2, repeatEvery: PRAJNA_TEMPLE_DECOR_PERIOD },
];

const PRAJNA_TEMPLE_VISUALS = {
  mapSet: "prajna-temple",
  backdrop: "cave",
  groundTopRows: 10,
  tileAnchor2x2: true,
  decorationSet: "prajna-temple-catalog",
  decorations: PRAJNA_TEMPLE_DECORATIONS,
  objectPattern: [],
};

const PRAJNA_TEMPLE_KINGS_ROOM_VISUALS = {
  mapSet: "prajna-temple",
  backdrop: "cave",
  tileAnchor2x2: true,
  decorations: [],
  objectPattern: [],
  mapStamp: "prajna-temple-kr-center",
  mapStampOnly: true,
};

// Crystal D2001 (BlackDragonDungeon entrance) — scrolling floor + repeating corridor edge (tools/build-bdd-*.ps1)
const BDD_DUNGEON_TILE_PATTERN = [
  [0, 2, 4, 1, 3, 0, 2, 4, 1, 3, 0, 2],
  [3, 1, 0, 4, 2, 3, 1, 0, 4, 2, 3, 1],
  [2, 4, 3, 0, 1, 2, 4, 3, 0, 1, 2, 4],
  [1, 0, 2, 3, 4, 1, 0, 2, 3, 4, 1, 0],
  [4, 3, 1, 2, 0, 4, 3, 1, 2, 0, 4, 3],
  [0, 1, 3, 4, 2, 0, 1, 3, 4, 2, 0, 1],
];

const BDD_1F_DECOR_PERIOD = 4000;
const BDD_1F_DECOR_ROWS = [-4.2, -3.4, -3.0, -2.6, -2.1, -1.6, -1.2, -0.8, 0.45, 0.75, 1.05, 1.35];
const BDD_1F_DECORATIONS = [
  // Sheet slots 0-6: #10 #12 #11 #14 #32 #28 #23
  { id: "bdd-catalog-10", slots: [0], worldX: 180, repeatEvery: BDD_1F_DECOR_PERIOD },
  { id: "bdd-catalog-12", slots: [1], worldX: 500, repeatEvery: BDD_1F_DECOR_PERIOD },
  { id: "bdd-catalog-11", slots: [2], worldX: 820, repeatEvery: BDD_1F_DECOR_PERIOD },
  { id: "bdd-catalog-14", slots: [3], worldX: 1140, repeatEvery: BDD_1F_DECOR_PERIOD },
  { id: "bdd-catalog-32", slots: [4], worldX: 1460, repeatEvery: BDD_1F_DECOR_PERIOD },
  { id: "bdd-catalog-28", slots: [5], worldX: 1780, repeatEvery: BDD_1F_DECOR_PERIOD },
  { id: "bdd-catalog-23", slots: [6], worldX: 2100, repeatEvery: BDD_1F_DECOR_PERIOD },
];

const BDD_1F_VISUALS = {
  mapSet: "bdd-dungeon",
  backdrop: "cave",
  decorationSet: "bdd-dungeon-catalog",
  groundTopRows: 5,
  groundBottomRows: 1,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
  decorationRows: BDD_1F_DECOR_ROWS,
  decorations: BDD_1F_DECORATIONS,
  objectPattern: [],
};

// Crystal D2001 room stamp — party stand at map (59, 98); tools/build-bdd-1f-stamp.ps1
const BDD_1F_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-1f-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2002 Black Snake Palace — party stand at map (22, 21); tools/build-bdd-2f-stamp.ps1
const BDD_2F_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-2f-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2005 Purgatory Hall — party stand at map (22, 26); tools/build-bdd-purgatory-stamp.ps1
const BDD_PURGATORY_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-purgatory-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2006 Wooma Palace (south pocket) — party stand at map (69, 71); tools/build-bdd-wooma-south-stamp.ps1
const BDD_WOOMA_SOUTH_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-wooma-south-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2006 Wooma Palace (north section) — party stand at map (19, 29); tools/build-bdd-wooma-north-stamp.ps1
const BDD_WOOMA_NORTH_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-wooma-north-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2007 HwanMaJin — party stand at map (131, 144); tools/build-bdd-hwanmajin-stamp.ps1
const BDD_HWANMAJIN_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-hwanmajin-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2008 Noble Hog Palace — party stand at map (65, 70); tools/build-bdd-noble-hog-stamp.ps1
const BDD_NOBLE_HOG_SOUTH_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-noble-hog-south-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2008 Noble Hog Palace north pocket — King Hog boss at map (29, 32); tools/build-bdd-noble-hog-north-stamp.ps1
const BDD_NOBLE_HOG_NORTH_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-noble-hog-north-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2010 HwanMaJin II — party stand at map (150, 128); tools/build-bdd-hmj2-stamp.ps1
const BDD_HMJ2_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-hmj2-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2011 Zuma Palace — party stand at map (28, 24); tools/build-bdd-zuma-palace-stamp.ps1
const BDD_ZUMA_PALACE_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-zuma-palace-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2012 Prison Hall — party stand at map (24, 24); tools/build-bdd-prison-hall-stamp.ps1
const BDD_PRISON_HALL_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-prison-hall-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

// Crystal D2013 Dark Devil Palace — party stand at map (27, 34); tools/build-bdd-dark-devil-stamp.ps1
const BDD_DARK_DEVIL_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "bdd-dark-devil-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

const ICE_HELL_KR_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "ice-hell-kr-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

const FLAME_QUEEN_KR_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "flame-queen-kr-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

const FLAMING_MUTANT_KR_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "flaming-mutant-kr-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

const SCALY_BEAST_KR_ROOM_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStamp: "scaly-beast-kr-center",
  mapStampOnly: true,
  stageMinWidth: 780,
  stageMinHeight: 480,
  stageMaxHeight: 540,
};

const DEAD_MINE_VISUALS = {
  backdrop: "cave",
  decorations: [],
  objectPattern: [],
  mapStampOnly: true,
};

export const MINING_SPOTS = [
  {
    id: "dead-mine-d405-52-30",
    label: "Ore Storage Place",
    mapStamp: "dead-mine-d405-52-30",
    arenaSpawnMap: { x: 54, y: 30 },
    arenaFocusMap: { x: 54, y: 30 },
  },
  {
    id: "dead-mine-d401-169-31",
    label: "Dead Mine East Tunnel",
    mapStamp: "dead-mine-d401-169-31",
    arenaSpawnMap: { x: 171, y: 32 },
    arenaFocusMap: { x: 171, y: 32 },
  },
  {
    id: "dead-mine-d401-47-52",
    label: "Dead Mine West Alcove",
    mapStamp: "dead-mine-d401-47-52",
    arenaSpawnMap: { x: 50, y: 53 },
    arenaFocusMap: { x: 50, y: 53 },
  },
  {
    id: "dead-mine-d403-86-69",
    label: "Dead Mine 1F Corridor",
    mapStamp: "dead-mine-d403-86-69",
    arenaSpawnMap: { x: 88, y: 69 },
    arenaFocusMap: { x: 88, y: 69 },
  },
];

export const PHASE1_ZONES = [
  {
    id: "zone-bicheon-1",
    label: "Bicheon 1",
    description: "Province outskirts",
    enemyIds: [29, 30, 39],
    rewards: { gold: [2, 8] },
  },
  {
    id: "zone-bicheon-2",
    label: "Bicheon 2",
    description: "Cat and Yob hunting route",
    enemyIds: [44, 42, 37],
    rewards: { gold: [5, 12] },
  },
  {
    id: "zone-bicheon-3",
    label: "Bicheon 3",
    description: "Oma, Yeti, and spider route",
    enemyIds: [48, 55, 46],
    rewards: { gold: [10, 20] },
  },
  {
    id: "zone-bone-cave-1",
    label: "Bone Cave 1",
    description: "Natural Cave entrance",
    enemyIds: [85, 81, 83, 84],
    rewards: { gold: [15, 35] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-bone-cave-2",
    label: "Bone Cave 2",
    description: "Deeper skeleton route",
    enemyIds: [90, 87, 92],
    rewards: { gold: [25, 50] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-bone-cave-kr",
    label: "Bone Cave KR",
    description: "King's Room boss loop",
    enemyIds: [94],
    rewards: { gold: [120, 220] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_KINGS_ROOM_TILE_PATTERN,
  },
  {
    id: "zone-dead-mines-1",
    label: "Dead Mines 1",
    description: "First zombie mine floor",
    enemyIds: [110, 112, 114, 116],
    rewards: { gold: [35, 70] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-dead-mines-2",
    label: "Dead Mines 2",
    description: "Deeper zombie mine floor",
    enemyIds: [122, 124, 126, 128, 130],
    rewards: { gold: [45, 90] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-dead-mines-kr",
    label: "Dead Mines KR",
    description: "Ghoul room",
    enemyIds: [118],
    rewards: { gold: [180, 320] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_KINGS_ROOM_TILE_PATTERN,
  },
  {
    id: "zone-kings-tomb",
    label: "Kings Tomb",
    description: "Oma King Spirit boss room",
    enemyIds: [291],
    rewards: { gold: [650, 1100] },
    arenaLaneY: 0.88,
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 14, y: 24 },
    arenaFocusMap: { x: 14, y: 24 },
    ...KINGS_TOMB_VISUALS,
  },
  {
    id: "zone-insect-cave-1",
    label: "Insect Cave 1",
    description: "Woomyon Woods insect cave entrance",
    enemyIds: [229, 233, 231],
    rewards: { gold: [50, 95] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-insect-cave-2",
    label: "Insect Cave 2",
    description: "Kek Tal and Horo Blaster route",
    enemyIds: [229, 231, 235, 237],
    rewards: { gold: [60, 110] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-insect-cave-kr",
    label: "Insect Cave KR",
    description: "Khazard boss loop",
    enemyIds: [239],
    rewards: { gold: [240, 420] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_KINGS_ROOM_TILE_PATTERN,
  },
  {
    id: "zone-wooma-temple-1",
    label: "Wooma Temple 1",
    description: "Temple entrance route",
    enemyIds: [240, 242, 244, 246, 248],
    rewards: { gold: [70, 130] },
    ...WOOMA_TEMPLE_VISUALS,
    tilePattern: WOOMA_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-wooma-temple-2",
    label: "Wooma Temple 2",
    description: "Inner temple route",
    enemyIds: [244, 246, 248, 250, 244, 246, 248, 250, 253],
    rewards: { gold: [85, 155] },
    ...WOOMA_TEMPLE_VISUALS,
    tilePattern: WOOMA_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-wooma-temple-kr",
    label: "Wooma Temple KR",
    description: "Wooma Taurus boss room",
    enemyIds: [256],
    rewards: { gold: [650, 1100] },
    arenaSpawnDistance: 180,
    ...WOOMA_TEMPLE_KINGS_ROOM_VISUALS,
    tilePattern: WOOMA_TEMPLE_KINGS_ROOM_TILE_PATTERN,
  },
  {
    id: "zone-bug-cave-1",
    label: "Bug Cave 1",
    description: "Mongchon worm cave entrance",
    enemyIds: [156, 154, 152, 158],
    rewards: { gold: [85, 145] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-bug-cave-2",
    label: "Bug Cave 2",
    description: "Deeper bug cave route",
    enemyIds: [156, 154, 152, 158, 150, 156, 154, 152, 158, 150, 160],
    rewards: { gold: [110, 185] },
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-bug-cave-kr",
    label: "Bug Cave KR",
    description: "Evil Centipede boss room",
    enemyIds: [166],
    rewards: { gold: [650, 1100] },
    arenaSpawnDistance: 180,
    arenaBossSpawnX: 300,
    arenaSpawnMap: { x: 83, y: 168 },
    arenaFocusMap: { x: 83, y: 168 },
    arenaEnemyOffsetY: 0,
    ...BUG_CAVE_KINGS_ROOM_VISUALS,
  },
  {
    id: "zone-stone-temple-1",
    label: "Stone Temple 1",
    description: "Angled stone tomb entrance",
    enemyIds: [261, 262, 263, 150],
    rewards: { gold: [95, 165] },
    ...STONE_TEMPLE_VISUALS,
    tilePattern: STONE_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-stone-temple-2",
    label: "Stone Temple 2",
    description: "Deeper stone tomb route",
    enemyIds: [261, 262, 264, 263, 261, 262, 264, 263, 261, 262, 264, 263, 265],
    rewards: { gold: [120, 200] },
    ...STONE_TEMPLE_VISUALS,
    tilePattern: STONE_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-stone-temple-kr",
    label: "Stone Tomb KR",
    description: "Evil Snake boss room",
    enemyIds: [266],
    rewards: { gold: [700, 1200] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 77, y: 28 },
    arenaFocusMap: { x: 77, y: 28 },
    ...STONE_TEMPLE_KINGS_ROOM_VISUALS,
  },
  {
    id: "zone-zuma-temple-1",
    label: "Zuma Temple 1",
    description: "Zuma temple entrance route",
    enemyIds: [267, 268, 263, 269],
    rewards: { gold: [130, 210] },
    ...ZUMA_TEMPLE_VISUALS,
    tilePattern: ZUMA_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-zuma-temple-2",
    label: "Zuma Temple 2",
    description: "Deeper zuma temple route",
    enemyIds: [267, 268, 269, 270, 271, 263, 267, 268, 269, 270],
    rewards: { gold: [155, 240] },
    ...ZUMA_TEMPLE_VISUALS,
    tilePattern: ZUMA_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-zuma-temple-kr",
    label: "Zuma Temple KR",
    description: "Zuma Taurus boss room",
    enemyIds: [272],
    rewards: { gold: [750, 1300] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 19, y: 24 },
    arenaFocusMap: { x: 19, y: 24 },
    ...ZUMA_TEMPLE_KINGS_ROOM_VISUALS,
  },
  {
    id: "zone-viper-cave-1",
    label: "Viper Cave 1",
    description: "Serpent Valley snake cave entrance",
    enemyIds: [410, 411, 410, 411, 410, 411],
    rewards: { gold: [190, 310] },
    ...VIPER_CAVE_VISUALS,
    tilePattern: STONE_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-viper-cave-2",
    label: "Viper Cave 2",
    description: "Deeper viper cave route",
    enemyIds: [412, 413, 412, 413, 415],
    rewards: { gold: [230, 380] },
    ...VIPER_CAVE_VISUALS,
    tilePattern: STONE_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-viper-cave-kr",
    label: "Viper Cave KR",
    description: "Yimoogi nest",
    enemyIds: [414],
    rewards: { gold: [850, 1400] },
    arenaSpawnDistance: 180,
    ...VIPER_CAVE_KINGS_ROOM_VISUALS,
    tilePattern: STONE_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-prajna-cave-1",
    label: "Prajna Cave 1",
    description: "Prajna stone cave entrance",
    enemyIds: [273, 274, 275, 276, 277],
    rewards: { gold: [165, 260] },
    ...PRAJNA_CAVE_VISUALS,
    tilePattern: PRAJNA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-prajna-cave-2",
    label: "Prajna Cave 2",
    description: "Deeper prajna stone cave route",
    enemyIds: [273, 274, 275, 276, 277, 278, 273, 274, 275, 276, 277, 278],
    rewards: { gold: [190, 290] },
    ...PRAJNA_CAVE_VISUALS,
    tilePattern: PRAJNA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-prajna-cave-kr",
    label: "Prajna Cave KR",
    description: "Bone Lord boss room",
    enemyIds: [279],
    rewards: { gold: [650, 1150] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 194, y: 242 },
    arenaFocusMap: { x: 194, y: 242 },
    ...PRAJNA_CAVE_KINGS_ROOM_VISUALS,
  },
  {
    id: "zone-prajna-temple-1",
    label: "Prajna Temple 1",
    description: "Prajna temple entrance — mostly minotaurs",
    enemyIds: [280, 280, 280, 280, 280, 280, 280, 280, 281, 282, 283, 284, 285, 286],
    rewards: { gold: [220, 340] },
    ...PRAJNA_TEMPLE_VISUALS,
    tilePattern: PRAJNA_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-prajna-temple-2",
    label: "Prajna Temple 2",
    description: "Deeper prajna temple — guards as common as elementals",
    enemyIds: [280, 281, 282, 283, 284, 285, 286, 280, 281, 282, 283, 284, 285, 286],
    rewards: { gold: [260, 390] },
    ...PRAJNA_TEMPLE_VISUALS,
    tilePattern: PRAJNA_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-prajna-temple-kr",
    label: "Prajna Temple KR",
    description: "Minotaur King boss room — D2079 center",
    enemyIds: [287],
    rewards: { gold: [650, 1200] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 50, y: 50 },
    arenaFocusMap: { x: 50, y: 50 },
    ...PRAJNA_TEMPLE_KINGS_ROOM_VISUALS,
    tilePattern: PRAJNA_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-bdd-1",
    label: "Black Dragon Dungeon 1F",
    description: "Evil Tongs and Evil Snake — Crystal BDD floor mobs (EvilTongs20 / EvilSnake20)",
    groupDungeon: "bdd",
    groupDungeonFloor: 1,
    groupDungeonWavesPerFloor: 5,
    enemyIds: [
      288, 289, 288, 289, 288, 289, 288, 289,
      288, 289, 288, 289, 288, 289, 288, 289,
      288, 289, 288, 289, 288, 289, 288, 289,
      288, 289, 288, 289,
    ],
    rewards: { gold: [240, 380] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 59, y: 98 },
    arenaFocusMap: { x: 59, y: 98 },
    ...BDD_1F_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-2",
    label: "King Scorpion's Cave",
    description: "King Scorpion boss room — Crystal Black Snake Palace (D2002)",
    groupDungeon: "bdd",
    groupDungeonFloor: 2,
    groupDungeonBoss: true,
    groupDungeonBossRespawnMinutes: 30,
    enemyIds: [292],
    rewards: { gold: [420, 680] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 22, y: 21 },
    arenaFocusMap: { x: 22, y: 21 },
    ...BDD_2F_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-3",
    label: "Purgatory Hall",
    description: "Crystal BDD connector (D2005) — Ghoul, Zuma Archer, Red Boar, Zuma Statue, Wedge Moth, Black Maggot",
    groupDungeon: "bdd",
    groupDungeonFloor: 3,
    groupDungeonWavesPerFloor: 5,
    groupDungeonWaveSpawnBase: 20,
    groupDungeonWaveSpawnStep: 5,
    groupDungeonWaveSpawnCap: 40,
    enemyIds: [
      297, 298, 299, 300, 301, 302,
      297, 298, 299, 300, 301, 302,
      297, 298, 299, 300, 301, 302,
      297, 298, 299, 300, 301, 302,
      297, 298, 299, 300,
    ],
    rewards: { gold: [320, 520] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 22, y: 26 },
    arenaFocusMap: { x: 22, y: 26 },
    ...BDD_PURGATORY_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-4",
    label: "Wooma Palace (South)",
    description: "Crystal WoomaPalace south pocket (D2006) — three Incarnated Wooma Taurus emerge on a timer",
    groupDungeon: "bdd",
    groupDungeonFloor: 4,
    groupDungeonBossSwarm: true,
    groupDungeonBossRespawnMinutes: 60,
    groupDungeonBossSwarmConfig: {
      templateId: 306,
      totalSpawns: 3,
      spawnIntervalMs: 15000,
      firstSpawnDelayMs: 0,
    },
    enemyIds: [306],
    rewards: { gold: [500, 800] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 69, y: 71 },
    arenaFocusMap: { x: 69, y: 71 },
    ...BDD_WOOMA_SOUTH_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-5",
    label: "Wooma Palace (North)",
    description: "Crystal WoomaPalace north route (D2006) — Ghoul21, ZumaArcher21, WoomaGuardian6, Zuma Guardian, and Zuma Statue waves",
    groupDungeon: "bdd",
    groupDungeonFloor: 5,
    groupDungeonWavesPerFloor: 5,
    groupDungeonWaveSpawnBase: 20,
    groupDungeonWaveSpawnStep: 5,
    groupDungeonWaveSpawnCap: 40,
    enemyIds: [
      303, 304, 305, 307, 308,
      303, 304, 305, 307, 308,
      303, 304, 305, 307, 308,
      303, 304, 305, 307, 308,
      303, 304, 305, 307, 308,
    ],
    rewards: { gold: [480, 760] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 19, y: 29 },
    arenaFocusMap: { x: 19, y: 29 },
    ...BDD_WOOMA_NORTH_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-6",
    label: "HwanMaJin",
    description: "Crystal HwanMaJin (D2007) — +50% BDD wave mobs: Ghoul, Zuma Archer, Zuma Statue, Zuma Guardian, White Boar, Wedge Moth",
    groupDungeon: "bdd",
    groupDungeonFloor: 6,
    groupDungeonWavesPerFloor: 5,
    groupDungeonWaveSpawnBase: 20,
    groupDungeonWaveSpawnStep: 5,
    groupDungeonWaveSpawnCap: 40,
    enemyIds: [
      315, 309, 310, 311, 312, 313,
      315, 309, 310, 311, 312, 313,
      315, 309, 310, 311, 312, 313,
      315, 309, 310, 311, 312, 313,
      315, 309, 310, 311, 312, 313,
    ],
    rewards: { gold: [520, 820] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 131, y: 144 },
    arenaFocusMap: { x: 131, y: 144 },
    ...BDD_HWANMAJIN_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-7",
    label: "Noble Hog Palace (South)",
    description: "Crystal Noble Hog Palace east pocket (D2008) — +50% BDD wave mobs (one per type): Zuma Archer, Zuma Statue, Zuma Guardian, White Boar, Wedge Moth",
    groupDungeon: "bdd",
    groupDungeonFloor: 7,
    groupDungeonWavesPerFloor: 5,
    groupDungeonWaveSpawnBase: 20,
    groupDungeonWaveSpawnStep: 5,
    groupDungeonWaveSpawnCap: 40,
    enemyIds: [309, 310, 311, 312, 313],
    rewards: { gold: [560, 880] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 65, y: 70 },
    arenaFocusMap: { x: 65, y: 70 },
    ...BDD_NOBLE_HOG_SOUTH_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-8",
    label: "Noble Hog Palace (North)",
    description: "Crystal Noble Hog Palace north pocket (D2008) — King Hog boss room",
    groupDungeon: "bdd",
    groupDungeonFloor: 8,
    groupDungeonBoss: true,
    groupDungeonBossRespawnMinutes: 90,
    enemyIds: [316],
    rewards: { gold: [720, 1120] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 29, y: 32 },
    arenaFocusMap: { x: 29, y: 32 },
    ...BDD_NOBLE_HOG_NORTH_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-10",
    label: "HwanMaJin II",
    description: "Crystal HwanMaJin second section (D2010) east cluster — Zuma Archer, Zuma Statue, Zuma Guardian, White Boar, Wedge Moth",
    groupDungeon: "bdd",
    groupDungeonFloor: 9,
    groupDungeonWavesPerFloor: 5,
    groupDungeonWaveSpawnBase: 20,
    groupDungeonWaveSpawnStep: 5,
    groupDungeonWaveSpawnCap: 40,
    enemyIds: [
      309, 310, 311, 312, 313,
      309, 310, 311, 312, 313,
      309, 310, 311, 312, 313,
      309, 310, 311, 312, 313,
      309, 310, 311, 312, 313,
    ],
    rewards: { gold: [760, 1180] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 150, y: 128 },
    arenaFocusMap: { x: 150, y: 128 },
    ...BDD_HMJ2_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-11",
    label: "Zuma Palace",
    description: "Crystal Zuma Palace (D2011) — Incarnated Zuma Taurus leads from the center row; two Incarnated Red Thunder Zuma join after 5s",
    groupDungeon: "bdd",
    groupDungeonFloor: 10,
    groupDungeonBossSwarm: true,
    groupDungeonBossRespawnMinutes: 120,
    groupDungeonBossSwarmConfig: {
      spawnQueue: [
        { templateId: 317, count: 1, lane: 0 },
        { templateId: 318, count: 2, spawnDelayMs: 5000, lanes: [-1, 1] },
      ],
      firstSpawnDelayMs: 0,
    },
    enemyIds: [317, 318],
    rewards: { gold: [800, 1240] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 28, y: 24 },
    arenaFocusMap: { x: 28, y: 24 },
    ...BDD_ZUMA_PALACE_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-12",
    label: "Prison Hall",
    description: "Crystal Prison Hall (D2012) east pocket — Zuma Archer, Zuma Statue, Zuma Guardian, Wedge Moth",
    groupDungeon: "bdd",
    groupDungeonFloor: 11,
    groupDungeonWavesPerFloor: 5,
    groupDungeonWaveSpawnBase: 20,
    groupDungeonWaveSpawnStep: 5,
    groupDungeonWaveSpawnCap: 40,
    enemyIds: [309, 310, 311, 313],
    rewards: { gold: [820, 1280] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 24, y: 24 },
    arenaFocusMap: { x: 24, y: 24 },
    ...BDD_PRISON_HALL_ROOM_VISUALS,
  },
  {
    id: "zone-bdd-13",
    label: "Dark Devil Palace",
    description: "Crystal Dark Devil Palace (D2013) — Dark Devil final BDD boss",
    groupDungeon: "bdd",
    groupDungeonFloor: 12,
    groupDungeonBoss: true,
    groupDungeonBossRespawnMinutes: 240,
    groupDungeonBossReinforcements: true,
    groupDungeonBossReinforcementsConfig: {
      templateId: 309,
      spawnIntervalMs: 2000,
      firstSpawnDelayMs: 2000,
      maxLiving: 16,
    },
    enemyIds: [319],
    rewards: { gold: [960, 1500] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 27, y: 34 },
    arenaFocusMap: { x: 27, y: 34 },
    ...BDD_DARK_DEVIL_ROOM_VISUALS,
  },
  {
    id: "zone-manectric-king-kr",
    label: "Ice Hell KR",
    description: "Manectric King boss room — Crystal IceHellTemple_KR (HELL206)",
    enemyIds: [293],
    rewards: { gold: [520, 820] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 88, y: 44 },
    arenaFocusMap: { x: 88, y: 44 },
    ...ICE_HELL_KR_ROOM_VISUALS,
  },
  {
    id: "zone-flame-queen-kr",
    label: "Flame Queen KR",
    description: "Flame Queen boss room — Crystal low-HP room nuke pattern",
    enemyIds: [294],
    rewards: { gold: [560, 900] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 50, y: 50 },
    arenaFocusMap: { x: 50, y: 50 },
    ...FLAME_QUEEN_KR_ROOM_VISUALS,
  },
  {
    id: "zone-flaming-mutant-kr",
    label: "Flaming Mutant KR",
    description: "Flaming Mutant boss room — Battle System arena (Hell_Bosss)",
    enemyIds: [295],
    rewards: { gold: [540, 860] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 96, y: 90 },
    arenaFocusMap: { x: 96, y: 90 },
    ...FLAMING_MUTANT_KR_ROOM_VISUALS,
  },
  {
    id: "zone-scaly-beast-kr",
    label: "Scaly Beast KR",
    description: "Scaly Beast boss room — stomp AoE + paralysis",
    enemyIds: [296],
    rewards: { gold: [480, 760] },
    arenaSpawnDistance: 180,
    arenaSpawnMap: { x: 83, y: 85 },
    arenaFocusMap: { x: 83, y: 85 },
    ...SCALY_BEAST_KR_ROOM_VISUALS,
  },
  {
    id: "zone-lab-stone-colossus",
    label: "Lab: Stone Colossus",
    description: "Decoded Mir3Mobs Mon1 test fight",
    enemyIds: [901],
    rewards: { gold: [0, 0] },
    arenaSpawnDistance: 180,
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_KINGS_ROOM_TILE_PATTERN,
  },
  {
    id: "zone-lab-overseer",
    label: "Lab: Overseer",
    description: "Decoded Killmaster Mobs 2 Mon25 test fight",
    enemyIds: [902],
    rewards: { gold: [0, 0] },
    arenaSpawnDistance: 180,
    ...WOOMA_TEMPLE_VISUALS,
    tilePattern: WOOMA_TEMPLE_KINGS_ROOM_TILE_PATTERN,
  },
  {
    id: "zone-lab-halberd-lord",
    label: "Lab: Halberd Lord",
    description: "Decoded Mon51 test fight",
    enemyIds: [903],
    rewards: { gold: [0, 0] },
    arenaSpawnDistance: 180,
    ...PRAJNA_TEMPLE_VISUALS,
    tilePattern: PRAJNA_TEMPLE_TILE_PATTERN,
  },
  {
    id: "zone-lab-white-boar",
    label: "Lab: White Boar",
    description: "Decoded NewMobsMagic Mon6 test fight",
    enemyIds: [904],
    rewards: { gold: [0, 0] },
    arenaSpawnDistance: 180,
    ...OMA_CAVE_VISUALS,
    tilePattern: OMA_CAVE_TILE_PATTERN,
  },
  {
    id: "zone-bichon-mine",
    label: "Dead Mines",
    description: "Crystal Dead Mines ore veins",
    miningOnly: true,
    enemyIds: [],
    rewards: { gold: [0, 0] },
    ...DEAD_MINE_VISUALS,
  },
  {
    id: "zone-training-academy",
    label: "Academy",
    description: "Crystal map 0110 — Trainer dummy",
    trainingRoom: true,
    enemyIds: [290],
    rewards: { gold: [0, 0] },
    arenaSpawnDistance: 120,
    arenaSpawnMap: { x: 11, y: 15 },
    arenaFocusMap: { x: 8, y: 12 },
    ...TRAINING_ROOM_VISUALS,
  },
];
