export const SPELL_TO_BODY = {
  None: "standing",

  Fencing: "attack1",
  Slaying: "attack1",
  Thrusting: "attack1",
  HalfMoon: "attack1",
  TwinDrakeBlade: "attack1",
  FlamingSword: "attack1",
  LionRoar: "spell",
  BladeAvalanche: "attack3",
  ProtectionField: "spell",
  Rage: "spell",
  CounterAttack: "attack1",
  SlashingBurst: "attack1",
  Fury: "spell",
  ImmortalSkin: "spell",

  FireBall: "spell",
  Repulsion: "spell",
  ElectricShock: "spell",
  GreatFireBall: "spell",
  HellFire: "spell",
  ThunderBolt: "spell",
  Teleport: "spell",
  FireBang: "spell",
  FireWall: "spell",
  Lightning: "spell",
  FrostCrunch: "spell",
  ThunderStorm: "spell",
  MagicShield: "spell",
  TurnUndead: "spell",
  Vampirism: "spell",
  IceStorm: "spell",
  FlameDisruptor: "spell",
  Mirroring: "spell",
  FlameField: "spell",
  Blizzard: "spell",
  MagicBooster: "spell",
  MeteorStrike: "spell",
  IceThrust: "spell",
  FastMove: "spell",
  StormEscape: "spell",

  Healing: "spell",
  SpiritSword: "spell",
  Poisoning: "spell",
  SoulFireBall: "spell",
  SummonSkeleton: "spell",
  Hiding: "spell",
  MassHiding: "spell",
  SoulShield: "spell",
  Revelation: "spell",
  BlessedArmour: "spell",
  EnergyRepulsor: "spell",
  TrapHexagon: "spell",
  Purification: "spell",
  MassHealing: "spell",
  Hallucination: "spell",
  UltimateEnhancer: "spell",
  SummonShinsu: "spell",
  Reincarnation: "spell",
  SummonHolyDeva: "spell",
  Curse: "spell",
  Plague: "spell",
  PoisonCloud: "spell",
  EnergyShield: "spell",
  PetEnhancer: "spell",
  HealingCircle: "spell",

  BattleCry: "spell",
  MeteorShower: "spell",
};

export const SPELL_GROUPS = [
  { label: "Common", items: ["None"] },
  {
    label: "Warrior",
    items: [
      "Fencing",
      "Slaying",
      "Thrusting",
      "HalfMoon",
      "TwinDrakeBlade",
      "FlamingSword",
      "LionRoar",
      "BladeAvalanche",
      "ProtectionField",
      "Rage",
      "CounterAttack",
      "SlashingBurst",
      "Fury",
      "ImmortalSkin",
    ],
  },
  {
    label: "Wizard",
    items: [
      "FireBall",
      "Repulsion",
      "ElectricShock",
      "GreatFireBall",
      "HellFire",
      "ThunderBolt",
      "Teleport",
      "FireBang",
      "FireWall",
      "Lightning",
      "FrostCrunch",
      "ThunderStorm",
      "MagicShield",
      "TurnUndead",
      "Vampirism",
      "IceStorm",
      "FlameDisruptor",
      "Mirroring",
      "FlameField",
      "Blizzard",
      "MagicBooster",
      "MeteorStrike",
      "IceThrust",
      "FastMove",
      "StormEscape",
    ],
  },
  {
    label: "Taoist",
    items: [
      "Healing",
      "SpiritSword",
      "Poisoning",
      "SoulFireBall",
      "SummonSkeleton",
      "Hiding",
      "MassHiding",
      "SoulShield",
      "Revelation",
      "BlessedArmour",
      "EnergyRepulsor",
      "TrapHexagon",
      "Purification",
      "MassHealing",
      "Hallucination",
      "UltimateEnhancer",
      "SummonShinsu",
      "Reincarnation",
      "SummonHolyDeva",
      "Curse",
      "Plague",
      "PoisonCloud",
      "EnergyShield",
      "PetEnhancer",
      "HealingCircle",
    ],
  },
];

export function bodyActionForSpell(spell) {
  return SPELL_TO_BODY[spell] ?? "spell";
}

export function spellLabel(spell) {
  return spell.replace(/([a-z0-9])([A-Z])/g, "$1 $2");
}
