export const BASIC_ATTACK_SKILL = {
  id: "None",
  label: "Basic Attack",
  bodyAction: "attack1",
  icon: 0,
  level1: 0,
  level2: 0,
  level3: 0,
  need1: 0,
  need2: 0,
  need3: 0,
  baseCost: 0,
  levelCost: 0,
  delayBase: 0,
  delayReduction: 0,
  powerBase: 0,
  powerBonus: 0,
  mPowerBase: 0,
  mPowerBonus: 0,
  multiplierBase: 1,
  multiplierBonus: 0,
  range: 0,
};

export const CRYSTAL_WARRIOR_SPELLS = [
  {
    id: "Fencing",
    label: "Fencing",
    shape: 1,
    icon: 2,
    bodyAction: "attack1",
    level1: 7,
    level2: 9,
    level3: 12,
    need1: 270,
    need2: 600,
    need3: 1300,
    baseCost: 0,
    levelCost: 0,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    passive: true,
    description: "Hitting Accuracy is increased per spell level.",
  },
  {
    id: "Slaying",
    label: "Slaying",
    shape: 2,
    icon: 6,
    bodyAction: "attack1",
    level1: 15,
    level2: 17,
    level3: 20,
    need1: 500,
    need2: 1100,
    need3: 1800,
    baseCost: 0,
    levelCost: 0,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    passive: true,
    combatPassive: true,
    description: "Your weapon becomes infused with strength.",
  },
  {
    id: "Thrusting",
    label: "Thrusting",
    shape: 3,
    icon: 11,
    bodyAction: "attack1",
    level1: 22,
    level2: 24,
    level3: 27,
    need1: 2000,
    need2: 3500,
    need3: 6000,
    baseCost: 0,
    levelCost: 0,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 0.25,
    multiplierBonus: 0.25,
    range: 0,
    toggle: true,
    secondCellOnly: true,
    description: "Toggle: attacks enemies in the second tile ahead.",
  },
  {
    id: "HalfMoon",
    label: "Half Moon",
    shape: 4,
    icon: 24,
    bodyAction: "attack1",
    level1: 26,
    level2: 28,
    level3: 31,
    need1: 5000,
    need2: 8000,
    need3: 14000,
    baseCost: 3,
    levelCost: 0,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 0.3,
    multiplierBonus: 0.1,
    range: 0,
    toggle: true,
    description: "Toggle: sweeps adjacent targets around you for bonus weapon damage.",
  },
  {
    id: "CrossHalfMoon",
    label: "Cross Half Moon",
    shape: 10,
    icon: 33,
    bodyAction: "attack1",
    level1: 38,
    level2: 40,
    level3: 42,
    need1: 7000,
    need2: 11000,
    need3: 16000,
    baseCost: 6,
    levelCost: 0,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 0.5,
    multiplierBonus: 0.1,
    range: 0,
    toggle: true,
    description: "Toggle: like Half Moon but splashes harder on other swarm rows; main-target damage matches a normal melee swing.",
  },
  {
    id: "TwinDrakeBlade",
    label: "Twin Drake Blade",
    shape: 6,
    icon: 37,
    bodyAction: "attack1",
    level1: 32,
    level2: 34,
    level3: 37,
    need1: 4000,
    need2: 6000,
    need3: 10000,
    baseCost: 10,
    levelCost: 0,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 0.6,
    multiplierBonus: 0.08,
    range: 0,
    description: "The weapon performs two swings in one motion.",
  },
  {
    id: "FlamingSword",
    label: "Flaming Sword",
    shape: 8,
    icon: 25,
    bodyAction: "attack1",
    level1: 35,
    level2: 37,
    level3: 40,
    need1: 2000,
    need2: 4000,
    need3: 6000,
    baseCost: 7,
    levelCost: 0,
    delayBase: 1800,
    delayReduction: 0,
    autoCooldownMs: 10000,
    toggleWindowMs: 10000,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1.4,
    multiplierBonus: 0.4,
    range: 0,
    description: "Summons the spirit of fire, causing a devastating blow.",
  },
  {
    id: "LionRoar",
    label: "Lion Roar",
    shape: 9,
    icon: 42,
    bodyAction: "spell",
    level1: 36,
    level2: 39,
    level3: 41,
    need1: 5000,
    need2: 8000,
    need3: 12000,
    baseCost: 14,
    levelCost: 4,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    description: "Releases a roar that disrupts nearby enemies.",
  },
  {
    id: "BladeAvalanche",
    label: "Blade Avalanche",
    shape: 11,
    icon: 43,
    bodyAction: "attack3",
    level1: 38,
    level2: 41,
    level3: 43,
    need1: 5000,
    need2: 8000,
    need3: 12000,
    baseCost: 14,
    levelCost: 4,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0.4,
    range: 0,
    description: "Hurls blades in three directions up to 3 tiles ahead. First two tiles full damage; third tile 60%. Uses MAC.",
  },
  {
    id: "ProtectionField",
    label: "Protection Field",
    shape: 12,
    icon: 50,
    bodyAction: "spell",
    level1: 39,
    level2: 42,
    level3: 45,
    need1: 6000,
    need2: 12000,
    need3: 18000,
    baseCost: 23,
    levelCost: 6,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    buff: true,
    description: "Adds 20–29% of your max AC to min and max AC for 45–90s (15s per skill level). Recast uses the normal spell delay only.",
  },
  {
    id: "Rage",
    label: "Rage",
    shape: 13,
    icon: 49,
    bodyAction: "spell",
    level1: 44,
    level2: 47,
    level3: 50,
    need1: 8000,
    need2: 14000,
    need3: 20000,
    baseCost: 20,
    levelCost: 5,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    buff: true,
    description: "Boosts min and max DC for 18–36s (6s per skill level). Bonus is 12% + 3%×level of your max DC at cast time.",
  },
  {
    id: "SlashingBurst",
    label: "Slashing Burst",
    shape: 15,
    icon: 55,
    bodyAction: "attack1",
    level1: 50,
    level2: 53,
    level3: 56,
    need1: 10000,
    need2: 16000,
    need3: 24000,
    baseCost: 25,
    levelCost: 4,
    delayBase: 14000,
    delayReduction: 4000,
    powerBase: 3,
    powerBonus: 0,
    mPowerBase: 1,
    mPowerBonus: 0,
    multiplierBase: 3.25,
    multiplierBonus: 0.25,
    range: 0,
    description: "Leaps from 1–6 tiles away to close into melee in zone combat; cannot be cast already in melee. In boss fights and dungeons, delivers a heavy burst slash only.",
  },
  {
    id: "Fury",
    label: "Fury",
    shape: 16,
    icon: 76,
    bodyAction: "spell",
    level1: 45,
    level2: 48,
    level3: 51,
    need1: 8000,
    need2: 14000,
    need3: 20000,
    baseCost: 10,
    levelCost: 4,
    delayBase: 600000,
    delayReduction: 120000,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    buff: true,
    description: "Increases attack speed by 4 for 60–90s (10s per skill level). Recast cooldown 10–4 min by level.",
  },
  {
    id: "ImmortalSkin",
    label: "Immortal Skin",
    shape: 17,
    icon: 80,
    bodyAction: "spell",
    level1: 60,
    level2: 61,
    level3: 62,
    need1: 1560,
    need2: 2200,
    need3: 3000,
    baseCost: 10,
    levelCost: 4,
    delayBase: 600000,
    delayReduction: 120000,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    buff: true,
    description: "Adds 10–31% of your max AC and MAC to min and max for ~60s, but reduces max DC by 5–8%. Recast cooldown 10–4 min by level.",
  },
];

export const CRYSTAL_WIZARD_SPELLS = [
  {
    id: "FireBall",
    label: "Fire Ball",
    shape: 31,
    icon: 0,
    bodyAction: "spell",
    level1: 7,
    level2: 9,
    level3: 11,
    need1: 200,
    need2: 350,
    need3: 700,
    baseCost: 3,
    levelCost: 2,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 2,
    powerBonus: 0,
    mPowerBase: 8,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Long distance attack by hurling a fireball.",
  },
  {
    id: "GreatFireBall",
    label: "Great Fire Ball",
    shape: 34,
    icon: 4,
    bodyAction: "spell",
    level1: 15,
    level2: 18,
    level3: 21,
    need1: 2000,
    need2: 2700,
    need3: 3500,
    baseCost: 5,
    levelCost: 1,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 10,
    powerBonus: 0,
    mPowerBase: 6,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "A powerful version of the Fire Ball spell.",
  },
  {
    id: "ThunderBolt",
    label: "Thunder Bolt",
    shape: 36,
    icon: 10,
    bodyAction: "spell",
    level1: 17,
    level2: 20,
    level3: 23,
    need1: 500,
    need2: 2000,
    need3: 3500,
    baseCost: 9,
    levelCost: 2,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 9,
    powerBonus: 0,
    mPowerBase: 8,
    mPowerBonus: 20,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Calls a thunderbolt to attack the target from the sky. Extra damage vs undead scales with skill level.",
  },
  {
    id: "FireWall",
    label: "Fire Wall",
    shape: 39,
    icon: 21,
    bodyAction: "spell",
    level1: 24,
    level2: 28,
    level3: 33,
    need1: 4000,
    need2: 10000,
    need3: 20000,
    baseCost: 30,
    levelCost: 5,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 3,
    powerBonus: 0,
    mPowerBase: 3,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Creates a wall of fire on the ground.",
  },
  {
    id: "FrostCrunch",
    label: "Frost Crunch",
    shape: 41,
    icon: 38,
    bodyAction: "spell",
    level1: 28,
    level2: 30,
    level3: 33,
    need1: 3000,
    need2: 5000,
    need3: 8000,
    baseCost: 15,
    levelCost: 3,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 12,
    powerBonus: 0,
    mPowerBase: 12,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Casts ice at the target with a chance to slow or freeze.",
  },
  {
    id: "IceStorm",
    label: "Ice Storm",
    shape: 46,
    icon: 32,
    bodyAction: "spell",
    level1: 35,
    level2: 37,
    level3: 40,
    need1: 4000,
    need2: 8000,
    need3: 12000,
    baseCost: 33,
    levelCost: 3,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 14,
    powerBonus: 0,
    mPowerBase: 12,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Casts a powerful ice storm that circles the enemy causing damage on rotation.",
  },
  {
    id: "Blizzard",
    label: "Blizzard",
    shape: 51,
    icon: 51,
    bodyAction: "spell",
    level1: 44,
    level2: 47,
    level3: 50,
    need1: 8000,
    need2: 16000,
    need3: 24000,
    baseCost: 65,
    levelCost: 10,
    autoCooldownMs: 15000,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 20,
    powerBonus: 5,
    mPowerBase: 30,
    mPowerBonus: 10,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Summons a blizzard over the target area; ticks may slow enemies.",
  },
  {
    id: "MagicShield",
    label: "Magic Shield",
    shape: 43,
    icon: 30,
    bodyAction: "spell",
    level1: 31,
    level2: 34,
    level3: 38,
    need1: 3000,
    need2: 7000,
    need3: 10000,
    baseCost: 35,
    levelCost: 5,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    buff: true,
    description: "Creates a protective field that reduces incoming damage.",
  },
  {
    id: "TurnUndead",
    label: "Turn Undead",
    shape: 44,
    icon: 31,
    bodyAction: "spell",
    level1: 32,
    level2: 35,
    level3: 39,
    need1: 3000,
    need2: 7000,
    need3: 10000,
    baseCost: 52,
    levelCost: 13,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Chance to kill eligible undead enemies in a single cast.",
  },
  {
    id: "Vampirism",
    label: "Vampirism",
    shape: 45,
    icon: 47,
    bodyAction: "spell",
    level1: 33,
    level2: 36,
    level3: 40,
    need1: 3000,
    need2: 5000,
    need3: 8000,
    baseCost: 26,
    levelCost: 13,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 12,
    powerBonus: 0,
    mPowerBase: 12,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Draws health from the victim to restore the caster.",
  },
  {
    id: "FlameDisruptor",
    label: "Flame Disruptor",
    shape: 47,
    icon: 34,
    bodyAction: "spell",
    level1: 38,
    level2: 40,
    level3: 42,
    need1: 5000,
    need2: 9000,
    need3: 14000,
    baseCost: 28,
    levelCost: 3,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 9,
    powerBonus: 0,
    mPowerBase: 15,
    mPowerBonus: 20,
    multiplierBase: 1.1,
    multiplierBonus: 0.3,
    range: 9,
    description: "Casts a powerful column of fire that burns its target.",
  },
  {
    id: "FlameField",
    label: "Flame Field",
    shape: 49,
    icon: 44,
    bodyAction: "spell",
    level1: 42,
    level2: 43,
    level3: 45,
    need1: 6000,
    need2: 11000,
    need3: 16000,
    baseCost: 83,
    levelCost: 8,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 25,
    powerBonus: 0,
    mPowerBase: 100,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    castGlobalLockMs: 2500,
    description: "Unleashes a huge burst of fire on the target area (Crystal damage; lands on the enemy like Ice Storm).",
  },
  {
    id: "Mirroring",
    label: "Mirroring",
    shape: 48,
    icon: 41,
    bodyAction: "spell",
    level1: 41,
    level2: 43,
    level3: 45,
    need1: 6000,
    need2: 11000,
    need3: 16000,
    baseCost: 21,
    levelCost: 0,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    buff: true,
    description: "Summons a mirror clone that stands behind you and follows as you travel (2–9 min by level).",
  },
  {
    id: "MagicBooster",
    label: "Magic Booster",
    shape: 51,
    icon: 73,
    bodyAction: "spell",
    level1: 47,
    level2: 49,
    level3: 52,
    need1: 12000,
    need2: 18000,
    need3: 24000,
    baseCost: 150,
    levelCost: 15,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    buff: true,
    description: "Reveals an enemy weakness for magical attacks.",
  },
  {
    id: "MeteorStrike",
    label: "Meteor Strike",
    shape: 52,
    icon: 52,
    bodyAction: "spell",
    level1: 49,
    level2: 52,
    level3: 55,
    need1: 15000,
    need2: 20000,
    need3: 25000,
    baseCost: 115,
    levelCost: 17,
    autoCooldownMs: 15000,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 20,
    powerBonus: 15,
    mPowerBase: 40,
    mPowerBonus: 10,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Summons molten rocks from the sky over the target area.",
  },
];

export const CRYSTAL_TAOIST_SPELLS = [
  {
    id: "Healing",
    label: "Healing",
    shape: 61,
    icon: 1,
    bodyAction: "spell",
    level1: 7,
    level2: 11,
    level3: 14,
    need1: 150,
    need2: 350,
    need3: 700,
    baseCost: 3,
    levelCost: 2,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 14,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    healing: true,
    description: "Heals yourself or a friendly target over time.",
  },
  {
    id: "SpiritSword",
    label: "Spirit Sword",
    shape: 62,
    icon: 3,
    bodyAction: "attack1",
    level1: 9,
    level2: 12,
    level3: 15,
    need1: 350,
    need2: 1300,
    need3: 2700,
    baseCost: 0,
    levelCost: 0,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    passive: true,
    description: "Increases the chance of hitting the target in melee combat.",
  },
  {
    id: "Poisoning",
    label: "Poisoning",
    shape: 63,
    icon: 5,
    bodyAction: "spell",
    level1: 14,
    level2: 17,
    level3: 20,
    need1: 700,
    need2: 1300,
    need3: 2700,
    baseCost: 2,
    levelCost: 1,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    debuff: true,
    description: "Throws poison to weaken the target.",
  },
  {
    id: "PoisonCloud",
    label: "Poison Cloud",
    shape: 83,
    icon: 54,
    bodyAction: "spell",
    level1: 43,
    level2: 45,
    level3: 48,
    need1: 4000,
    need2: 8000,
    need3: 12000,
    baseCost: 30,
    levelCost: 5,
    autoCooldownMs: 18000,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 20,
    powerBonus: 0,
    mPowerBase: 40,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    debuff: true,
    description: "Throws amulets and poison to create a toxic cloud on the target.",
  },
  {
    id: "Curse",
    label: "Curse",
    shape: 81,
    icon: 45,
    bodyAction: "spell",
    level1: 40,
    level2: 42,
    level3: 44,
    need1: 4000,
    need2: 6000,
    need3: 9000,
    baseCost: 17,
    levelCost: 3,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 20,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    debuff: true,
    description: "Throws an amulet to curse enemies in a wide area, weakening their attacks.",
  },
  {
    id: "Plague",
    label: "Plague",
    shape: 82,
    icon: 74,
    bodyAction: "spell",
    level1: 42,
    level2: 44,
    level3: 47,
    need1: 5000,
    need2: 9000,
    need3: 13000,
    baseCost: 20,
    levelCost: 5,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Throws an amulet and poison to unleash a plague on the target area.",
  },
  {
    id: "SoulFireBall",
    label: "Soul Fire Ball",
    shape: 64,
    icon: 12,
    bodyAction: "spell",
    level1: 18,
    level2: 21,
    level3: 24,
    need1: 1300,
    need2: 2700,
    need3: 4000,
    baseCost: 3,
    levelCost: 1,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 3,
    powerBonus: 0,
    mPowerBase: 8,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    description: "Throws a flaming amulet at the target.",
  },
  {
    id: "SummonSkeleton",
    label: "Summon Skeleton",
    shape: 65,
    icon: 16,
    bodyAction: "spell",
    level1: 19,
    level2: 22,
    level3: 26,
    need1: 1000,
    need2: 2000,
    need3: 3500,
    baseCost: 12,
    levelCost: 4,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    summon: true,
    description: "Summons a skeleton to fight beside the Taoist.",
  },
  {
    id: "SoulShield",
    label: "Soul Shield",
    shape: 69,
    icon: 13,
    bodyAction: "spell",
    level1: 22,
    level2: 24,
    level3: 26,
    need1: 2000,
    need2: 3500,
    need3: 7000,
    baseCost: 2,
    levelCost: 2,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    buff: true,
    description: "Blesses targets to strengthen magic defence.",
  },
  {
    id: "BlessedArmour",
    label: "Blessed Armour",
    shape: 71,
    icon: 14,
    bodyAction: "spell",
    level1: 25,
    level2: 27,
    level3: 29,
    need1: 4000,
    need2: 6000,
    need3: 10000,
    baseCost: 2,
    levelCost: 2,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    buff: true,
    description: "Blesses targets to strengthen physical defence.",
  },
  {
    id: "EnergyShield",
    label: "Energy Shield",
    shape: 84,
    icon: 57,
    bodyAction: "spell",
    level1: 48,
    level2: 51,
    level3: 54,
    need1: 5000,
    need2: 9000,
    need3: 13000,
    baseCost: 50,
    levelCost: 20,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    buff: true,
    description: "Cast on a friendly player. While active, attacks may restore HP (chance scales with Luck and skill level).",
  },
  {
    id: "MassHealing",
    label: "Mass Healing",
    shape: 75,
    icon: 28,
    bodyAction: "spell",
    level1: 31,
    level2: 33,
    level3: 36,
    need1: 2000,
    need2: 4000,
    need3: 8000,
    baseCost: 28,
    levelCost: 3,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 4,
    powerBonus: 0,
    mPowerBase: 10,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    healing: true,
    description: "Heals all injured allies in a 3×3 area around the target point.",
  },
  {
    id: "HealingCircle",
    label: "Healing Circle",
    shape: 86,
    icon: 82,
    bodyAction: "spell",
    level1: 39,
    level2: 41,
    level3: 43,
    need1: 7000,
    need2: 12000,
    need3: 15000,
    baseCost: 10,
    levelCost: 100,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    healing: true,
    description: "Creates a sacred circle under the Taoist that steadily heals nearby allies and pets.",
  },
  {
    id: "UltimateEnhancer",
    label: "Ultimate Enhancer",
    shape: 77,
    icon: 35,
    bodyAction: "spell",
    level1: 33,
    level2: 35,
    level3: 38,
    need1: 5000,
    need2: 7000,
    need3: 10000,
    baseCost: 28,
    levelCost: 4,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 9,
    buff: true,
    description: "Increases each class's primary offensive stat.",
  },
  {
    id: "SummonShinsu",
    label: "Summon Shinsu",
    shape: 78,
    icon: 29,
    bodyAction: "spell",
    level1: 35,
    level2: 37,
    level3: 40,
    need1: 2000,
    need2: 4000,
    need3: 6000,
    baseCost: 28,
    levelCost: 4,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    summon: true,
    description: "Summons a Shinsu to fight beside the Taoist.",
  },
  {
    id: "SummonHolyDeva",
    label: "Summon Holy Deva",
    shape: 80,
    icon: 40,
    bodyAction: "spell",
    level1: 38,
    level2: 41,
    level3: 43,
    need1: 4000,
    need2: 6000,
    need3: 9000,
    baseCost: 28,
    levelCost: 4,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    summon: true,
    description: "Summons a Holy Deva to attack monsters with thunder.",
  },
  {
    id: "PetEnhancer",
    label: "Pet Enhancer",
    shape: 85,
    icon: 78,
    bodyAction: "spell",
    level1: 45,
    level2: 48,
    level3: 51,
    need1: 4000,
    need2: 8000,
    need3: 12000,
    baseCost: 30,
    levelCost: 40,
    delayBase: 1800,
    delayReduction: 0,
    powerBase: 0,
    powerBonus: 0,
    mPowerBase: 0,
    mPowerBonus: 0,
    multiplierBase: 1,
    multiplierBonus: 0,
    range: 0,
    buff: true,
    petBuff: true,
    description: "Strengthens a summoned pet's attack power and physical/magic defence.",
  },
];

export const WARRIOR_COMBAT_SKILLS = [
  BASIC_ATTACK_SKILL,
  ...CRYSTAL_WARRIOR_SPELLS.filter((spell) => !spell.passive || spell.combatPassive),
];

export function warriorSpellById(spellId) {
  if (spellId === BASIC_ATTACK_SKILL.id) return BASIC_ATTACK_SKILL;
  return CRYSTAL_WARRIOR_SPELLS.find((spell) => spell.id === spellId) ?? null;
}

export function warriorSpellByShape(shape) {
  const id = Number(shape);
  return CRYSTAL_WARRIOR_SPELLS.find((spell) => spell.shape === id) ?? null;
}

export function taoistSpellById(spellId) {
  return CRYSTAL_TAOIST_SPELLS.find((spell) => spell.id === spellId) ?? null;
}

export function taoistSpellByShape(shape) {
  const id = Number(shape);
  return CRYSTAL_TAOIST_SPELLS.find((spell) => spell.shape === id) ?? null;
}

export function magicIconSrc(spell) {
  if (!spell || spell.icon == null) return "";
  const crystalSkillFrame = Number(spell.icon) * 2;
  return `./public/magic-icons/images/frame_${String(crystalSkillFrame).padStart(6, "0")}.png`;
}

export function spellMpCost(spell, learned) {
  if (!spell || spell.id === BASIC_ATTACK_SKILL.id) return 0;
  return Math.max(0, (Number(spell.baseCost) || 0) + (Number(learned?.level) || 0) * (Number(spell.levelCost) || 0));
}

export const CRYSTAL_SPELL_GLOBAL_LOCK_MS = 1800;

/** Undead-only damage multiplier by Thunder Bolt skill level (L0 unchanged vs legacy 1.5×). */
export const THUNDER_BOLT_UNDEAD_MULTIPLIER_BY_LEVEL = [1.5, 1.5, 1.8, 2.35];

export function thunderBoltUndeadMultiplier(spellLevel) {
  const level = Math.max(0, Math.min(3, Math.trunc(Number(spellLevel) || 0)));
  return THUNDER_BOLT_UNDEAD_MULTIPLIER_BY_LEVEL[level] ?? 1.5;
}

/** Cast/action lock from delayBase (not spell recharge). Use for next-attack gaps. */
export function spellActionDelayMs(spell, learned) {
  if (!spell || spell.id === BASIC_ATTACK_SKILL.id) return 0;
  return Math.max(0, (Number(spell.delayBase) || 0) - (Number(learned?.level) || 0) * (Number(spell.delayReduction) || 0));
}

/** Spell recharge delay. Prefer autoCooldownMs when set (e.g. Poison Cloud 18s). */
export function spellDelayMs(spell, learned) {
  if (!spell || spell.id === BASIC_ATTACK_SKILL.id) return 0;
  if (spell.autoCooldownMs) return Math.max(0, Number(spell.autoCooldownMs) || 0);
  return spellActionDelayMs(spell, learned);
}

// Crystal uses per-spell UserMagic.GetDelay() and also a global SpellTime lock (1800ms) on cast.
export function crystalSpellCastCooldownMs(spell, learned) {
  const globalLock = Math.max(
    CRYSTAL_SPELL_GLOBAL_LOCK_MS,
    Math.trunc(Number(spell?.castGlobalLockMs) || 0),
  );
  return Math.max(globalLock, spellDelayMs(spell, learned));
}

export function spellExperienceTarget(spell, level) {
  if (!spell || level >= 3) return 0;
  return [spell.need1, spell.need2, spell.need3][level] ?? 0;
}

export function spellLevelRequirement(spell, level) {
  if (!spell || level >= 3) return 0;
  return [spell.level1, spell.level2, spell.level3][level] ?? 0;
}
